### ISSUE TITLE
[GSSOC'21]Introductory Quiz

### ISSUE THREAD

**Issue by anumshka** [Praful932/Kitabe#103]
**Is your feature request related to a problem? Please describe.**
Sometimes, It is not always the case that we know about all the genres .A quick guide to this would be better.

**Describe the solution you'd like**
I would like to add a short quiz for the selecting a genre.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

Please assign this to me.
Thankyou.

**Comment by Praful932** [comment]
@anumshka Could you elaborate, quiz as in?
Check out the starter [guide](https://github.com/Praful932/Kitabe/discussions/42)

**Comment by anumshka** [comment]
A Quiz using html,css and javascript which asks a number of questions to the user regarding the book genre.For example,one may not know what is historic fiction,or Memoirs..or any simple genre as well.We may help the user to choose a genre even if he/she does not know how to name it.Based on the answers of his/her likes/dislikes in the quiz,we may suggest a particular genre to the person.

**Comment by maneprajakta** [comment]
@anumshka could you elaborate on how to implement it and when will it be visible to the user. Also, how will you implement it?

**Comment by maneprajakta** [comment]
@anumshka any updates?

**Comment by anumshka** [comment]
Like a set of 2-3 mcqs per genre..then calculating the marks for each genre..Storing them..and the winner is the genre with the highest points.We may give them some situations as well in the mcqs but it would be short and concise.
Really sorry for responding late.
Thankyou.

**Comment by Praful932** [comment]
@anumshka Where would you be displaying it? Could you show us a mockup?
