### ISSUE TITLE
Contributing details

### ISSUE THREAD

**Issue by PandeySomya77** [Praful932/Kitabe#105]
I can't find contributing details in the readme file

**Comment by PandeySomya77** [comment]
Can I work on this issue?

**Comment by Praful932** [comment]
Hi @PandeySomya77 check out the [starter guide ](https://github.com/Praful932/Kitabe/discussions/42) :)
There's already a [CONTRIBUTING.md file](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md)
