### ISSUE TITLE
Site loading Optimization

### ISSUE THREAD

**Issue by mohammedjameel24** [Praful932/Kitabe#106]
**Is your feature request related to a problem? Please describe.**

As soon as we address the site it loads the ui elements quicker than the main bg-image and other graphic components of website ,makes it look less Optimizated

**Describe the solution you'd like**

**Are you willing to contribute to this issue?** [Yes/No]

**Describe alternatives you've considered**

**Additional context**

**Comment by Praful932** [comment]
Please follow the PR template.

**Comment by mohammedjameel24** [comment]
Now @Praful932

**Comment by maneprajakta** [comment]
@mohammedjameel24 edited your PR description fill it accordingly.
