### ISSUE TITLE
Creating Filter options in book searching options

### ISSUE THREAD

**Issue by 435akashjha** [Praful932/Kitabe#107]
**Is your feature request related to a problem? Please describe.**
[and](url
![Screenshot 2021-03-17 034344](https://user-images.githubusercontent.com/49565671/111387050-22807f00-86d3-11eb-83e1-bdda7b2e2516.png)
In the book search section if there can be filter for finding different types of books such as self-help, comic , personality development, communication skills..etc

**Describe the solution you'd like**
when we search on youtube for any videos we can filter with channel, playlist , duration of content in the same way if there same done it can help users to find the book easily
**Are you willing to contribute to this issue?** [Yes/No]
yes
**Describe alternatives you've considered**

**Additional context**

**Comment by maneprajakta** [comment]
@435akashjha Could you elaborate on how you aim to implement it?

**Comment by 435akashjha** [comment]
I can create a dropdown list named as 'Category' and in that dropdown list ,input fields can be created of self help, personality development, communication, startup books using html, css and js

**Comment by Praful932** [comment]
@435akashjha We already have pages for each genre, would your change be search for genre as well as books? & If I click on genre then it will redirect to genre page
Is that what you mean

**Comment by 435akashjha** [comment]
The basic idea here to create this issue that user can find the books of choices by a category very easily .
eg: On this website when we search for job openings it contain filter options like this .
[
[
![Screenshot_2021-03-17-11-59-33-14](https://user-images.githubusercontent.com/49565671/111425081-a14bdb00-8718-11eb-85b0-49bc0e988c21.jpg)
](![Screenshot_2021-03-17-11-59-33-14](https://user-images.githubusercontent.com/49565671/111425047-95f8af80-8718-11eb-8bce-eecb1434c708.jpg))
](url)

**Comment by maneprajakta** [comment]
@435akashjha we already have a genre section which gives user option to explore by genre.

**Comment by Praful932** [comment]
@435akashjha exactly what @maneprajakta said, If you mean a feature for user to search and navigate to a genre, please elaborate or show a mockup how & where it will be
