### ISSUE TITLE
Feedback - Vedant Ghodke

### ISSUE THREAD

**Issue by VEDANTGHODKE** [Praful932/Kitabe#11]
The project looks amazing and the ReadMe file is indeed quite catchy and attractive. I did check the codes and saw that they need a few refinements and improvements. However, I also did observe that you have open issues for improvements already suggested. Just a friendly tip: Try and use individually worked content for feedbacks rather than co-authored work.

**Comment by Praful932** [comment]
> Try and use individually worked content for feedbacks rather than co-authored work.

Could you elaborate?

**Comment by VEDANTGHODKE** [comment]
I saw two contributors to your project. Try and circulate the projects that you have done by yourself only.

**Comment by Praful932** [comment]
The project was being built for quite some time and before **circulating and posting** the repository , I had asked for approval from Sir :) Neverthless the motive is not affected, the Project is Open Source, anyone can collaborate ⚡

Closing the Issue.
