### ISSUE TITLE
Adding a Search Icon in the Search bar

### ISSUE THREAD

**Issue by Sweeti-Gupta** [Praful932/Kitabe#111]
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to any problem. It's about making the page more attractive.

**Describe the solution you'd like**
I want to add a "Search Icon" in the "Search Bar" to give a better look to the project.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
As of now, I have no alternatives for this, I just want to add a "Search Icon" in the "Search Bar".

**Additional context**
![Screenshot (2706)_LI](https://user-images.githubusercontent.com/79096136/111525614-d2152a00-8783-11eb-9132-afc6705528e2.jpg)

@maneprajakta I want to contribute this as a part of GSSOC'21.Please assign this issue to me.

**Comment by maneprajakta** [comment]
@Sweeti-Gupta Please follow the issue template for creating an issue.

**Comment by Sweeti-Gupta** [comment]
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to any problem. It's about making the page more attractive.

**Describe the solution you'd like**
I want to add a "Search Icon" in the "Search Bar" to give a better look to the project.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
As of now, I have no alternatives for this, I just want to add a "Search Icon" in the "Search Bar".

**Additional context**
![Screenshot (2706)_LI](https://user-images.githubusercontent.com/79096136/111525614-d2152a00-8783-11eb-9132-afc6705528e2.jpg)

@maneprajakta I want to contribute this as a part of GSSOC'21.Please assign this issue to me.

**Comment by maneprajakta** [comment]
Go for it @Sweeti-Gupta.
Before starting go through [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) it will help you in contributing to the project.

**Comment by Sweeti-Gupta** [comment]
@maneprajakta Ok Ma'am! Thank you for assigning.

**Comment by ambivert-sam** [comment]
@maneprajakta mam can you please assign this issue to me?

**Comment by maneprajakta** [comment]
@ambivert-sam Thank you for showing interest but the issue is already assigned to someone.

**Comment by Praful932** [comment]
@ambivert-sam Go through the [starter guide](https://github.com/Praful932/Kitabe/discussions/42) :)

**Comment by maneprajakta** [comment]
@Sweeti-Gupta any updates?

**Comment by Sweeti-Gupta** [comment]
@maneprajakta Working on it.

**Comment by iampranavdhar** [comment]
Hey @maneprajakta,
In case if it is not solved yet can you assign me?
Thanks

**Comment by Praful932** [comment]
Hi @iampranavdhar This is currently assigned :)
Check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42) or [up-for-grab issues](https://github.com/Praful932/Kitabe/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc+no%3Aassignee)
