### ISSUE TITLE
We can add "Get in touch section" in the footer.

### ISSUE THREAD

**Issue by ASHISH-GITHUB2495** [Praful932/Kitabe#114]
**Features that we can add**
We can have a footer with Get in touch section ... you have option to fill name, email and message which will go directly to the admin.
Like the screenshot i have attach ...
if you like the idea I would like to contribute as GSSOC'21 participant.

**Screenshot**
![Screenshot (15)](https://user-images.githubusercontent.com/57385079/111493981-1690cd80-8764-11eb-97b4-b61ddd675184.png)

**Comment by Praful932** [comment]
@ASHISH-GITHUB2495 Check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42) :)
We already had similar issues #59
