### ISSUE TITLE
Improve The SEO (page speed)

### ISSUE THREAD

**Issue by Raghad-Khaled** [Praful932/Kitabe#116]
**Describe the bug**
the load speed of the pages is not the best speed it can be improved by decrease the image sizes and keep the image resolution too

# speed of the page
<img width="753" alt="Pgspeed" src="https://user-images.githubusercontent.com/60848147/111536894-7cd11c80-8773-11eb-9e9e-474493303d15.PNG">

# decrease the images sizes improve its speed
<img width="734" alt="images" src="https://user-images.githubusercontent.com/60848147/111536971-92dedd00-8773-11eb-86ab-e5ddc4ad18e8.PNG">

**Comment by maneprajakta** [comment]
@Raghad-Khaled Thanks for showing interest. Please follow the issue template for creating an issue. Then only we can move forward.
