### ISSUE TITLE
Create Contact us page

### ISSUE THREAD

**Issue by fatma-sia27** [Praful932/Kitabe#119]
Hey, I think there must be a "Contact Us" page in the nav bar so that anyone who wanted to work with you all like if anyone wants to be a front-end developer of your website "Kitabe" then they can easily contact you all through the contact form . Also if any viewer want to ask some questions about any book or author then they can contact you easily. I think this would be good for your websitw, if you find it useful you can assign this issue to me , I  will definitely make a contact form page for your website.
Thank you

**Comment by Praful932** [comment]
@fatma-sia27 We had a similar issue #45
