### ISSUE TITLE
Activating Environment on Linux

### ISSUE THREAD

**Issue by shikha-16** [Praful932/Kitabe#122]
**Describe the bug**
When trying to activate the environment, I faced an error.

**To Reproduce**
1. Go to '[Contributing.md](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md)'
2. Scroll down to 'Setting up the Project'
4. See error in 

Activate the environment -

For Linux/Unix OS : source bookenv/Scripts/activate
For Windows OS: bookenv\Scripts\activate

**Screenshots**
![image](https://user-images.githubusercontent.com/68149849/111810297-dd8b6100-88fb-11eb-9795-3d9f7e3de7b6.png)

**Are you willing to contribute to this issue?** 
Yes

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04

**Comment by maneprajakta** [comment]
@shikha-16 plz follow the issue template for creating an issue.
I have edited your issue description fill it accordingly.

**Comment by shikha-16** [comment]
> @shikha-16 plz follow the issue template for creating an issue.
> I have edited your issue description fill it accordingly.

I have done so, please review @maneprajakta

**Comment by maneprajakta** [comment]
@shikha-16 Go ahead with this one.
