### ISSUE TITLE
Book Series Page

### ISSUE THREAD

**Issue by Rhutwi** [Praful932/Kitabe#128]
**Is your feature request related to a problem? Please describe.**
As a fan of books in series it is hard to find the next part in a series novel or even get a list of a particular order in which the series goes.Also it hard to say from the book if it is series or a single book.The reader only gets to know that after reading.

Another problem that i think me and other avid readers face is finding a book with the perfect ending.Now we don't want to know what happened in the end but it would be good if we knew if it was a good one or a bad one before reading.Sad endings are the worst.

**Describe the solution you'd like**:
I want to make page where people can just look for series books and an instant list is generated of the order of books and it also shows a description of the previous book.

For people willing to take risk and have a glance at spoilers we can devote another page to spoilers.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
When the books are displayed it should show if the book is series or not and if it is it should show the next book or a list of upcoming books in the same page as other recommended books.

**Comment by maneprajakta** [comment]
@Rhutwi 
- The idea of having a page devoted to books with series seems nice to me.
- Not clear about spoiler page and also book with bad and sad end what you mean can you elaborate?
Also, you need to think about how you aim to implement it.

**Comment by Rhutwi** [comment]
Sure i'll work upon the series page and  about the spoiler page it is for people who want to know the ending before reading the book.Only for those people we can show the ending in one line description.of course the page will be separate and will be named spoilers.

**Comment by maneprajakta** [comment]
@Rhutwi 
It's a big issue
- If you go for the series page could you tell us how you will do this same for the spoiler page ?

**Comment by Praful932** [comment]
@Rhutwi I'm still not clear about the spoilers page, What exactly will you be showing there and from where?

**Comment by Rhutwi** [comment]
Okay sure should i work upon the series page first then? As for the spoiler page i just have this idea that we can fetch the ending of each book and show it as spoiler for those who want to know the ending.
I can do the spoiler page afterwards but should i start with series page?

**Comment by Praful932** [comment]
@Rhutwi I don't think we would need a spoilers page, doesn't really match with our goal. You can do the series page, but we would need details on how you would implement that, we already have a lot of separate pages for books

**Comment by Rhutwi** [comment]
Okay sure i will drop the idea of spoilers.
For series page i will add tag for books that are in series.The goodreads API allows us to see if all series by an author and if a book is in a series. i'd like to extract that information and add that as a tag, and all books with that  tag will have a seperate page. 

Do you think i should change anything about this approach? If not please assign me this issue.

**Comment by Praful932** [comment]
@maneprajakta Wdyt, we wouldn't want to crowd the navbar more, need to think if we can do it in an existing page

**Comment by maneprajakta** [comment]
@Praful932 yep.
@Rhutwi what you can do is add a button or something like that in the book card itself which we currently have which will be visible when for a book if that book occurs in a series. On clicking that it would open up a page with all books in series of that.

**Comment by Rhutwi** [comment]
Sure i can do that.... That sounds good. Can i implement that @Praful932 ?

**Comment by Praful932** [comment]
Yes, that would be nice, go ahead @Rhutwi Check out the [guidelines ](https://github.com/Praful932/Kitabe/discussions/42) first and then start
Happy hacking :)

**Comment by Praful932** [comment]
@Rhutwi Any updates? You can open a WIP/Draft PR so we can track that you are going in the right direction :)

**Comment by Rhutwi** [comment]
Sure i will open it by tomorrow.

**Comment by maneprajakta** [comment]
@Rhutwi any updates?

**Comment by Rhutwi** [comment]
Hello I have  semester exams from tomorrow. Is it okay if I make a PR after some time?

**Comment by maneprajakta** [comment]
@Rhutwi No issues.
All the best for exam :rocket:

**Comment by maneprajakta** [comment]
@Rhutwi any updates?

**Comment by maneprajakta** [comment]
@Praful932 what you say?should we close this issue or unassign.

**Comment by Rhutwi** [comment]
Sorry my family is suffering from COVID-19 and i too have the symptoms so i couldn't work on the issue.. though i am trying to solve it as fast as i can.. Sorry for the delay or lack of response from my side.

**Comment by maneprajakta** [comment]
@Rhutwi No worries.
Hope everyone gets recovered soon🤞
Take care of your health and your family.
Surely, we will keep the issue open. So, whenever you feel you can start working on it but we need to unassign you as the project is open for contribution everyone should get a chance.

**Comment by Rhutwi** [comment]
Sure thank you for understanding.

**Comment by Praful932** [comment]
@Rhutwi Take care and hope everyone gets well 💜
You can always contribute later :)

**Comment by Sanjana-03** [comment]
Hello I want to work in this issue what I have to do can you explain me??

**Comment by Sanjana-03** [comment]
Hello I want to work on this issue what I have to do can you explain me??

**Comment by Praful932** [comment]
@Sanjana-03 you can check out the previous conversation, If there any doubts ping one of us

**Comment by maneprajakta** [comment]
@Praful932 shall we close this issue. What do you say?

**Comment by Praful932** [comment]
Yes, With the new updates, we won't be needing this anymore.
