### ISSUE TITLE
Using description to find similar books

### ISSUE THREAD

**Issue by knmehta12** [Praful932/Kitabe#129]
**Is your feature request related to a problem? Please describe.**
It's not a problem . I just think that titles and genres provide a foundation for the recommendation system and description of a book can be added as a feature that also determines if other books are similar

**Describe the solution you'd like**
I'd like to implement a cosine similarity using book descriptions/plots to make the system more accurate  

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
No I have none as of now.

**Additional context**
N/A

**Comment by maneprajakta** [comment]
@knmehta12 have you gone through the [dataset](https://github.com/zygmuntz/goodbooks-10k) we don't have book description in the dataset.We have [function](https://github.com/Praful932/Kitabe/blob/0fb9a735afb787a3674aec5a8ec8d0dfae648d34/templates/mainapp/layout.html#L184) which gives book summary.

**Comment by knmehta12** [comment]
Yes I saw the dataset, my original issue was going to be adding description to books. But since we have that already, we can make a table, or add a column for this and then use it in the algorithm, right?
Should I change anything in this approach?

**Comment by maneprajakta** [comment]
@knmehta12 
so we get a column with a book description after that in what way you will proceed further?
Assigning you for this.

**Comment by Praful932** [comment]
@knmehta12 Could you detail out your implementation details, How will you be doing this exactly?

**Comment by knmehta12** [comment]
Hello. I haven't figured that out in too much detail. But like you've used titles [here](https://colab.research.google.com/drive/1LRr4Nm2I2HRJUTXbRea3sK5A1Bvp_lav), to get recommendations, the same way (using cosine similarity), I want to use description/summary to get similar books. Is that alright?

**Comment by Praful932** [comment]
@knmehta12 Yes you can, the problem with the book summary is that there are certain bugs since it is scraped, you can use that(would need a fix), also the results need to be convincing when description is used and better than the title approach

**Comment by knmehta12** [comment]
I actually found a library called isbnlib that gives a small description of the book so that works right?

**Comment by Praful932** [comment]
Yea, go ahead, instead of removing the current title approach we can add it to the current recommendation approach

**Comment by Praful932** [comment]
@knmehta12 Any updates? You can open a WIP/Draft PR so we can track that you are going in the right direction :)

**Comment by knmehta12** [comment]
@Praful932 Sure I'll do that now.

**Comment by knmehta12** [comment]
Hello I have exams from tomorrow. Is it okay if I make a PR after this week?

**Comment by maneprajakta** [comment]
@knmehta12 No issues.
All the best for exams :+1:

**Comment by knmehta12** [comment]
Hello I ran into a problem and I am clueless as to how to proceed. Can I get some help please?

Some descriptions aren't in English so they are Non-ASCII characters and so I cannot put it in any model. I tried looking up transliterating but I'm not so sure it helps. What should I do next? Should I replace those with their title and author name?

Thank you very much.

**Comment by maneprajakta** [comment]
@knmehta12 What method did you used . Check if this [Library](https://py-googletrans.readthedocs.io/en/latest/) could help.

**Comment by maneprajakta** [comment]
@knmehta12 any updates?

**Comment by knmehta12** [comment]
Hi @maneprajakta I'm working on it. it's almost done. It'll take a day more maximum. :)

**Comment by knmehta12** [comment]
Hello I'm uploading mu notebook in my WIP branch. please let me know if I should change anything?

**Comment by Praful932** [comment]
@knmehta12 It is worth a shot, you could try improving it and see if any change is visible on the recommendations

**Comment by knmehta12** [comment]
I tried to change a few things like ngram and changing order of description and title in soup. It works a little for titles that are in Japanese  :)

**Comment by maneprajakta** [comment]
Great :rocket:.

**Comment by knmehta12** [comment]
Hello. Just to be sure I have to replace cosine_rating_sim.npz inside static/mainapp right? I actually couldn't find the code of the model inside so I was confused. Thank you for helping.

**Comment by maneprajakta** [comment]
Yes

**Comment by knmehta12** [comment]
The file that I'm trying to upload is 146MB. And github isn't letting me upload it. It also says that even if I do use LFS and upload it, it won't be pushed. What do you think I should do? Thank you.

**Comment by Praful932** [comment]
Hi @knmehta12 , could you show an example of how it compares to the existing similarity, we would like to validate it and only add it if it performs better, Check the notebooks section for the earlier file

**Comment by knmehta12** [comment]
Yes absolutely.

**Comment by Praful932** [comment]
A [google collab](https://colab.research.google.com/) notebook would be great

**Comment by knmehta12** [comment]
I uploaded the book in my WIP branch long ago. Is it not there?

**Comment by Praful932** [comment]
It is, Mentioned collab because we will be able to run it and check directly

**Comment by knmehta12** [comment]
Right. I'm sorry. I did it now. Is this fine?

**Comment by knmehta12** [comment]
Hello. Should I open another branch for uploading the dataset and link?

**Comment by maneprajakta** [comment]
You can create a fresh PR with all changes in it.

**Comment by subhangi2731** [comment]
@maneprajakta please assign this to me

**Comment by maneprajakta** [comment]
@subhangi2731 thanks for showing interest it's already assigned to @knmehta12
