### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by Abg4real** [Praful932/Kitabe#13]
Hi @Praful932 and @maneprajakta 
I went through your project and I really liked it a lot.
The idea of good books being recommended to is fascinating to a bookworm like me.
Here are some suggestions:
1. The logo on the left side of the home screen is smaller in size.
2. The images you are using are of quite high quality and it seems to hamper the loading time of the website. Try using a image-size compressor like [this](https://www.npmjs.com/package/imagemin) (sorry I have no idea about the python package with similar function 😅).
3. The color palette for the website is a bit dull. Try adding some contrasting and fresh colors. Refer [this](https://mycolor.space/).

Regards,
Abhishek

**Comment by Praful932** [comment]
Thanks for the feedback @Abg4real, Will add these issues to the project [tracker](https://github.com/Praful932/Kitabe/projects/1). Meanwhile do let us know if you would like to take up any of these issues and contribute :)

**Comment by Abg4real** [comment]
Sure!

**Comment by maneprajakta** [comment]
Thankyou :star2:  for the feedback @Abg4real , will surely look forward to these suggestions.

**Comment by Abg4real** [comment]
🙌😄

**Comment by Praful932** [comment]
#15 Solved 2. The slow loading time is due to heroku server location and speed.
@maneprajakta Any takes on 3?
@Abg4real Could you elaborate on 1?
This could have been 3 separate issues 😄

**Comment by Abg4real** [comment]
![image](https://user-images.githubusercontent.com/55308761/101987187-92d4ca00-3cb8-11eb-8ecc-063a7611e381.png)
As you can see, the font of the logo on top left corner is smaller compared to standard logo sizes. 2rem font size would look better.

**Comment by Praful932** [comment]
Ok are you willing to make a PR for this?

**Comment by Abg4real** [comment]
sure no problem. But I think the PR will an overkill for a mere font size change.

**Comment by Praful932** [comment]
I meant this issue except the images part

**Comment by Abg4real** [comment]
Oh.
Sure no problem.
I'll create one soon.

**Comment by Praful932** [comment]
#26 Fixes this 🚀
