### ISSUE TITLE
Link Each Book to Wikipedia

### ISSUE THREAD

**Issue by SalmaZakaria** [Praful932/Kitabe#130]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to add a link to each card of the book to link it to a Wikipedia page that talks about it, to let the user know more about it.

**Are you willing to contribute to this issue?** [Yes/No]
Yes, I am GSSOC'21 Participant.

**Comment by maneprajakta** [comment]
@SalmaZakaria Idea seems cool to me.
Can you elaborate on how you aim to implement this?

**Comment by RahulBansal0502** [comment]
We can do two things in it. First, we can refer the user to Wikipedia where he/she can get more about it. Secondly, we can contact any e-commerce company like Amazon or Flipkart where we refer the user to these platforms if he/she wants to buy a book.

**Comment by SalmaZakaria** [comment]
@maneprajakta 
In every book card, there will be a link to direct it to the page it talks about it, it will be updated in the Html file of the project

**Comment by maneprajakta** [comment]
@SalmaZakaria we think that adding the reference to other sites will decrease time spent by users on our website. So, closing the issue.
