### ISSUE TITLE
Adding a 404 page

### ISSUE THREAD

**Issue by ShambhaviSharma0110** [Praful932/Kitabe#132]
**Is your feature request related to a problem? Please describe.**
I would like to add a 404 page 

**Describe the solution you'd like**
404 page will be displayed every time a path that is unknown is entered.

**Are you willing to contribute to this issue?** Yes

**Describe alternatives you've considered**

**Additional context**
Once approved I would upload a screenshot as well

**Comment by Praful932** [comment]
@ShambhaviSharma0110 +1 if you put in a page like [this](https://freefrontend.com/html-funny-404-pages/), in accordance with the theme of the website

**Comment by prerna2712** [comment]
Can I work on this?

**Comment by maneprajakta** [comment]
@ShambhaviSharma0110 are you going to work on this?

**Comment by Rishita0606** [comment]
Hello! I am interested to work on this issue if it isn't assigned yet.

**Comment by maneprajakta** [comment]
@prerna2712 Go ahead with this :rocket: before that read our [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42).
Also, go through above comments.

**Comment by ShambhaviSharma0110** [comment]
@maneprajakta I've already made a 404 page I was just waiting to get assigned and make a pr...

**Comment by maneprajakta** [comment]
> @ShambhaviSharma0110 are you going to work on this?

.

**Comment by maneprajakta** [comment]
@ShambhaviSharma0110 No issues but we do expect some replies.

**Comment by maneprajakta** [comment]
@prerna2712 check out other issues that we have for project.

**Comment by ShambhaviSharma0110** [comment]
yes ofc I'm really sorry for late replies I'll create a pr in just about an hour...

**Comment by prerna2712** [comment]
> @prerna2712 check out other issues that we have for project.
Okay sure

**Comment by arpit456jain** [comment]
can I work on this issue?

**Comment by maneprajakta** [comment]
@arpit456jain thanks for showing interest the issue is assigned already. Go through our [starter guide](https://github.com/Praful932/Kitabe/discussions/42) :)

**Comment by arpit456jain** [comment]
@maneprajakta I had made a 404 page and added the backend for showing this page if 404 error occurs kindly review it.

https://user-images.githubusercontent.com/55352601/113545832-86c69c80-9608-11eb-8449-00a0edbbad49.mp4

If its ok may I create a PR

**Comment by maneprajakta** [comment]
@arpit456jain 
This is nice but if you could do something like this [examples](https://freefrontend.com/html-funny-404-pages/) 
or this 
![Screenshot from 2021-04-02 13-29-51](https://user-images.githubusercontent.com/57425995/113557257-589e8800-961b-11eb-863d-60f1e1acaa96.png)

- Maintain theme of the website take help of codepen and [canva](https://www.canva.com/) to get the animations you can even get images on canva.

**Comment by arpit456jain** [comment]
Ok @maneprajakta i will try

**Comment by Praful932** [comment]
@arpit456jain No problem with the debug variable, it's set to False in production, we will review accordingly after a PR is made :)

**Comment by arpit456jain** [comment]
Ok @Praful932

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by Praful932** [comment]
@simranbhalla3 This is already assigned :)
Check out [up-for-grab issues](https://github.com/Praful932/Kitabe/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee) or the [starter guide](https://github.com/Praful932/Kitabe/discussions/42)

**Comment by arpit456jain** [comment]
@Praful932 kindly review my PR
