### ISSUE TITLE
Improvising Navbar

### ISSUE THREAD

**Issue by dsrao711** [Praful932/Kitabe#138]
The Navbar can be improved
Current :
![image](https://user-images.githubusercontent.com/59830064/111991715-9f2fb500-8b3a-11eb-8ade-258f742e18b0.png)
We can improvise it by adding the icon beside the text . Please check the example below:
![image](https://user-images.githubusercontent.com/59830064/111992068-02214c00-8b3b-11eb-882e-88e0692bb52b.png)

I would to like to work on this issue as a GSSOC '21 participant

**Comment by Praful932** [comment]
@dsrao711 Please follow issue template, have a look at other issues

**Comment by maneprajakta** [comment]
@dsrao711 we alreadu have a issue for same #137
