### ISSUE TITLE
Login/signup toggle functionality

### ISSUE THREAD

**Issue by Inventor77** [Praful932/Kitabe#141]
**Is your feature request related to a problem? Please describe.**
Login and Sign In page takes different two pages and also taking too much space in  Navigation Bar Makes UI bit clumsy 

**The solution**
Enhancing the UI Of Signin and login page into one also adding Dynamic functionality by toggling  between them in one single page and also adding interactive Animation also making UI of Navbar more user friendly 

**Are you willing to contribute to this issue?** [Yes]

**Additional context**
Mentors, it is a considerable amount of change in the concept of overall website, so the thing I ask is to let me make the necessary changes in my own remote version to which I will showcase the website after bringing some changes and if it is considerable enough to be implemented, 
Can Mentors overlook on this and feels if it is worth changing Please assign me this issue and labeling it with **gssoc21**

**Comment by Praful932** [comment]
Hi @Inventor77, check out the [guidelines](https://github.com/Praful932/Kitabe/discussions/42), We would need the concept & design to match with the theme of the website and also think along the lines how you will display login & signup when logged in & not

**Comment by Inventor77** [comment]
> Hi @Inventor77, check out the [guidelines](https://github.com/Praful932/Kitabe/discussions/42), We would need the concept & design to match with the theme of the website and also think along the lines how you will display login & signup when logged in & not

Yes Sir I will work on it and soon Give it's Solution but Please Assign me this Issue I that I have Created

**Comment by maneprajakta** [comment]
ok, go ahead.

**Comment by maneprajakta** [comment]
@Inventor77 any updates?

**Comment by Inventor77** [comment]
> @Inventor77 any updates?

Yes Mam I'm for on it, I enhanced the Navbar. I'm familiar with Flash but Not Django so it's taking me little Time to integrate two files and making a Animation. I have to be Careful since integrating Login and SignUp file can Affect other too.

**Comment by Praful932** [comment]
> > @Inventor77 any updates?
> 
> Yes Mam I'm for on it, I enhanced the Navbar. I'm familiar with Flash but Not Django so it's taking me little Time to integrate two files and making a Animation. I have to be Careful since integrating Login and SignUp file can Affect other too.

That's alright, you can open a WIP/Draft PR so that we also know that you're going in the right direction & help out if needed :)

**Comment by Inventor77** [comment]
Yes Sir, thats the best Option too. 
But I think doing alone will Help me learn more.

**Comment by Praful932** [comment]
> Yes Sir, thats the best Option too.
> But I think doing alone will Help me learn more.

Up to you :) Whatever you feel best

**Comment by Praful932** [comment]
@Inventor77 you can open a WIP PR. so we are aware it's being worked upon as you push commits..
Just @Praful932 is fine, no need of sir

**Comment by Inventor77** [comment]
> @Inventor77 you can open a WIP PR. so we are aware it's being worked upon as you push commits..
> Just @Praful932 is fine, no need of sir

Yes sir I will do it today itself

**Comment by maneprajakta** [comment]
No updates recieved
