### ISSUE TITLE
[Feature] [GSSOC' 21] Adding Facebook auth to the app

### ISSUE THREAD

**Issue by Aditya201551** [Praful932/Kitabe#142]
**Is your feature request related to a problem? Please describe.**
- It would be more convenient that user has the option to log in with Facebook to this app, as it would provide more authentication option to users 

**Describe the solution you'd like**
- I would like to add the feature of Facebook login to this project by using developers.facebook.com's login API

**Are you willing to contribute to this issue?** [Yes/No]
- YES

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Praful932** [comment]
Thanks for your interest :) @Aditya201551 , We believe google auth is all we we'll need for now.
Check out [up-for-grab issues](https://github.com/Praful932/Kitabe/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee) or the [guidelines ](https://github.com/Praful932/Kitabe/discussions/42)
