### ISSUE TITLE
Arrange books side by side in Library

### ISSUE THREAD

**Issue by nidhivanjare** [Praful932/Kitabe#145]
**Is your feature request related to a problem? Please describe.**
On the library page, each book is taking a large space and the user will have to scroll more. So we can align books in a different manner. 

**Describe the solution you'd like**
we can display 2 books side by side. 

**Are you willing to contribute to this issue?** [Yes/No]
Yes

I am a GSSOC'21 participant I would like to contribute to this issue.

**Comment by Praful932** [comment]
@nidhivanjare Need more description & detail with screenshots check out [any other sample issues](https://github.com/Praful932/Kitabe/issues/30)

**Comment by nidhivanjare** [comment]
Library Page Display          |  What I want it to look like
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/55665104/112743910-248eeb80-8fb9-11eb-8b36-5180ed096059.png)  |  ![](https://user-images.githubusercontent.com/55665104/112743922-412b2380-8fb9-11eb-9a9c-8f5a0d525aee.png)



If we display the cards side by side in the library page then the user has to scroll less and can view more. I think it will be a good UI / UX change in the website.

**Comment by Praful932** [comment]
@nidhivanjare We would want the same current UI for library, what you could do is arrange them side by side and paginate accordingly, there will be backend change too
Is that what you mean?

**Comment by nidhivanjare** [comment]
Yes, I just want to arrange them side by side !!

**Comment by Praful932** [comment]
Sure go ahead

**Comment by shreya-gb** [comment]
May I work on this? @nidhivanjare

**Comment by Praful932** [comment]
Hi @shreya-gb This is already assigned :)
Check out [up-for-grab issues](https://github.com/Praful932/Kitabe/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee) or the [starter guide](https://github.com/Praful932/Kitabe/discussions/42)
