### ISSUE TITLE
Limit Characters shown in Book Cards

### ISSUE THREAD

**Issue by Sonaljain6431** [Praful932/Kitabe#148]
**Is your feature request related to a problem? Please describe.**
Some of the book tiles doesn't clearly show up the details as all the book tile have the same size while some of the book description and book name are large. Thus description gets hidden behind buttons.

**Describe the solution you'd like**

It can be done by:
1. Making the image of the book small
2. Increasing the size of that particular tile
3. Reducing the spacing between description
4. Decreasing the padding of the content inside tile

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**

**Additional context**
![issue](https://user-images.githubusercontent.com/52230497/112743812-1be9e580-8fb8-11eb-8cfd-03ec29804c5b.png)

**Comment by maneprajakta** [comment]
@Sonaljain6431  We don't want the card design to be changed for the genre page. If you could suggest other alternatives like one could be fixing the no of lines to be displayed for book name and author name.

**Comment by Sonaljain6431** [comment]
The padding or font-size of the text can be decreased.

**Comment by maneprajakta** [comment]
@Sonaljain6431 adding bottom padding to author name would work what you say?

**Comment by Sonaljain6431** [comment]
It can increase the size of the card design if card is not set to box-sizing

**Comment by maneprajakta** [comment]
Also fixing the line to be displayed for the book title will work

**Comment by Sonaljain6431** [comment]
It indirectly involves changing the font size

**Comment by Sonaljain6431** [comment]
Can I work on this issue?

**Comment by maneprajakta** [comment]
> It can increase the size of the card design if card is not set to box-sizing

True
So go for fixing lines to be displayed for book title or book author would work check [this](https://github.com/Praful932/Kitabe/blob/f664d589f1af33e48655731d574b343fdb910d81/templates/mainapp/index.html#L373) for same

**Comment by maneprajakta** [comment]
> Can I work on this issue?

Go ahed

**Comment by Sonaljain6431** [comment]
Ok

**Comment by maneprajakta** [comment]
Go through [starter guide](https://github.com/Praful932/Kitabe/discussions/42) it will help.

**Comment by maneprajakta** [comment]
@Sonaljain6431 you need to do this to explore and genre-wise book displayed page.

**Comment by Sonaljain6431** [comment]
> Go through [starter guide](https://github.com/Praful932/Kitabe/discussions/42) it will help.

Okay mam!

**Comment by saniikakulkarni** [comment]
Is it ok if work on this issue?
I can also improve UI of the tile.

**Comment by saniikakulkarni** [comment]
Is it ok if I work on this issue?
I can also improve UI of the book tile.
