### ISSUE TITLE
Enhacing typeface

### ISSUE THREAD

**Issue by sonaljain067** [Praful932/Kitabe#149]
**Is your feature request related to a problem? Please describe.**
On the login and sign-up page, more than 3 types of font-styles are used which don't look professional and consistent.

**Describe the solution you'd like**
Changing the fonts to a type of font that would be looking consistent and premium look. For example, adding 2 or a maximum of 3 fonts that would be a little similar to one another like a Helvetica, Frutiger, and Arial font could make it more appealing to users.  But now it doesn't look much appealing and readable as different font-styles like different forms of cursive and Arial fonts are used on a single page.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**

**Additional context**
Before
![Screenshot from 2021-04-02 17-15-55](https://user-images.githubusercontent.com/52230497/113412984-4b915700-93d7-11eb-954f-c43958f7daad.png)

After
![Screenshot from 2021-04-01 14-41-00](https://user-images.githubusercontent.com/52230497/113271662-64770b00-92f8-11eb-9bdd-36e379d67f9f.png)

**Comment by Praful932** [comment]
@Sonaljain6431 Could you add an example to the issue description, what you expect it to be, then vs now scenario?

**Comment by Sonaljain6431** [comment]
Sure

**Comment by Praful932** [comment]
@Sonaljain6431 Could you show the expected typeface/a mockup?

**Comment by Sonaljain6431** [comment]
Yeah, sure!

**Comment by Sonaljain6431** [comment]
Something like this!

> **Is your feature request related to a problem? Please describe.**
> On the login and sign-up page, more than 3 types of font-styles are used which don't look professional and consistent.
> 
> **Describe the solution you'd like**
> Changing the fonts to a type of font that would be looking consistent and premium look. For example, adding 2 or a maximum of 3 fonts that would be a little similar to one another like a Helvetica, Frutiger, and Arial font could make it more appealing to users. But now it doesn't look much appealing and readable as different font-styles like different forms of cursive and Arial fonts are used on a single page.
> 
> **Are you willing to contribute to this issue?** [Yes/No]
> Yes
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> ![Screenshot from 2021-04-01 14-41-00](https://user-images.githubusercontent.com/52230497/113271662-64770b00-92f8-11eb-9bdd-36e379d67f9f.png)

**Comment by maneprajakta** [comment]
@Sonaljain6431 a mockup we mean showing font-style that you wish to replace.

**Comment by Sonaljain6431** [comment]
> **Is your feature request related to a problem? Please describe.**
> On the login and sign-up page, more than 3 types of font-styles are used which don't look professional and consistent.
> 
> **Describe the solution you'd like**
> Changing the fonts to a type of font that would be looking consistent and premium look. For example, adding 2 or a maximum of 3 fonts that would be a little similar to one another like a Helvetica, Frutiger, and Arial font could make it more appealing to users. But now it doesn't look much appealing and readable as different font-styles like different forms of cursive and Arial fonts are used on a single page.
> 
> **Are you willing to contribute to this issue?** [Yes/No]
> Yes
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Before
> ![Screenshot from 2021-04-02 17-15-55](https://user-images.githubusercontent.com/52230497/113412984-4b915700-93d7-11eb-954f-c43958f7daad.png)
> 
> After
> ![Screenshot from 2021-04-01 14-41-00](https://user-images.githubusercontent.com/52230497/113271662-64770b00-92f8-11eb-9bdd-36e379d67f9f.png)

Is this appropriate?

**Comment by maneprajakta** [comment]
@sonaljain067 
- Approving the buttons 
- But the form content as it's informative its text cursive doesn't look appropriate.
- Also if possible try if you could add a google icon in `sign in with google button`
- not sure about nav bar font but you can try we will discuss in PR further chnages.
- Also changes needs to be done on both pages `login` and `signup`
Assigning you go ahead :rocket:

**Comment by sonaljain067** [comment]
Ok

**Comment by iaryangoyal** [comment]
is this still open?

**Comment by Praful932** [comment]
@iaryangoyal This is assigned, check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42) :)
