### ISSUE TITLE
feat: Adding hover effect to cards in "Read Genre Wise"

### ISSUE THREAD

**Issue by iampranavdhar** [Praful932/Kitabe#157]
### Is your feature request related to a problem? Please describe.
The hover effect is given to "Read Genre Wise" is given to complete div which doesn't seem to be interactive for the users.

### Describe the solution you'd like
It would be nice if we give a hover effect to each card instead. I don't know it's by mistake or intentional but if you feel the same that it should be corrected, Assign it to be happy to work on it.

### Additional context

![image](https://user-images.githubusercontent.com/73348574/112885921-ea276a80-90ee-11eb-8f4e-ca3e690b08ac.png)

Here when we hover on it complete div is elevating.

**Comment by maneprajakta** [comment]
@iampranavdhar follow the issue template for creating an issue.

**Comment by iampranavdhar** [comment]
@maneprajakta Can you take a look into this now?

**Comment by maneprajakta** [comment]
@iampranavdhar go for it. Once go through [starter guide](https://github.com/Praful932/Kitabe/discussions/42) it will help in contributing to the project.

**Comment by iampranavdhar** [comment]
Okay, Thanks for assigning. I will work on it and send a PR as soon as possible.

**Comment by iampranavdhar** [comment]
@maneprajakta Had done the changes. can you look into PR?

Thanks.
