### ISSUE TITLE
Fix "Sign In With Google" 

### ISSUE THREAD

**Issue by nidhivanjare** [Praful932/Kitabe#161]
**Describe the bug**
The "Sign In with google option is not working"

**To Reproduce**

I would like to fix this error to help the users sign in with google easily. 

**Expected behavior**
Users should be able to log in or sign up using the "Sign in with Google" Button 

**Screenshots**

<img width="942" alt="Screenshot 2021-03-30 at 4 31 00 PM" src="https://user-images.githubusercontent.com/55665104/112978938-90b64e80-9175-11eb-9786-3d941b4f6bf1.png">
<img width="1437" alt="Screenshot 2021-03-30 at 4 27 00 PM" src="https://user-images.githubusercontent.com/55665104/112978953-94e26c00-9175-11eb-8d52-db57bb04cfbe.png">

**Are you willing to contribute to this issue?** 
Yes

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser 
 - chrome, safari
 - Version 14.0.3

**Smartphone (please complete the following information):**
 - Device: iphone Xs Max
 - OS:  iOS 14.4.2
 - Browser  safari , chrome
 - Version 14.0.3

**Comment by maneprajakta** [comment]
@nidhivanjare on the local host it won't work. Your environment doesn't have social account keys in it. check out on our [website](https://kitabe-app.herokuapp.com/)
