### ISSUE TITLE
Making improvements for the Search bar

### ISSUE THREAD

**Issue by kulendu** [Praful932/Kitabe#167]
Making improvements for the Search bar. 
<br>
| Before | After (changes I proposed)|
| ----------- | ----------- |
|![Annotation 2021-04-01 184233](https://user-images.githubusercontent.com/56751963/113299360-6baf1080-931a-11eb-8e08-0fed0a26859a.png)|   ![Annotation 2021-04-01 184416](https://user-images.githubusercontent.com/56751963/113299514-9305dd80-931a-11eb-8726-3b4f10e6e0ea.png)|

Previously the search bar was almost close to the center. So I think making it closer to the other menus and increasing the **border-radius** a bit will look better.

**Comment by Praful932** [comment]
@kulendu Please follow the issue template :)

**Comment by Praful932** [comment]
Yes

**Comment by kulendu** [comment]
Ok.... Fine

**Comment by Praful932** [comment]
The fix looks nice, why was this closed? @kulendu

**Comment by kulendu** [comment]
Actually you said to follow the templatings. So I closed this one and opened the new one with the features templates..... 

Both the fixes are same

**Comment by Praful932** [comment]
Oh alright, you could have just edited this one, everything in the issue is editable :)
Np, just keep it in mind next time
