### ISSUE TITLE
Improving  Search box

### ISSUE THREAD

**Issue by kulendu** [Praful932/Kitabe#168]
- **Is your feature request related to a problem? Please describe.**
Making improvements for the Search bar. Previously the search bar was almost close to the center, so thought of improving it.

- **Describe the solution you'd like**
Previously the search bar was almost close to the center, and I think it should be a separate part from the logo and the other sections. So I think making it closer to the other menus and increasing the **border-radius** a bit will look better. 

- **Are you willing to contribute to this issue?** [Yes/No]
Yes

- **Additional context**
The proposed solution is demonstrated below :

  **Before:** 
![Annotation 2021-04-01 184233](https://user-images.githubusercontent.com/56751963/113320542-3b726c80-9330-11eb-87e0-ea8c4111ce96.png)
  **After (if the proposed solution is made):**
![Annotation 2021-04-01 184416](https://user-images.githubusercontent.com/56751963/113320586-47f6c500-9330-11eb-93dc-945554e50fb6.png)

**Comment by kulendu** [comment]
@Praful932  I have closed the previous issue and created a new one with the templating. Please have a look 👍 

Thank you

**Comment by maneprajakta** [comment]
@kulendu go ahead with this one. Go through  [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) once.

**Comment by kulendu** [comment]
Ya sure 😁

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by Praful932** [comment]
@srishtij2000 This is assigned :), check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42)
