### ISSUE TITLE
Customized Scrollbar

### ISSUE THREAD

**Issue by Saatvik21** [Praful932/Kitabe#169]
**Is your feature request related to a problem? Please describe.**

Currently, the scrollbar doesn't go well with the background of the webpages.

**Describe the solution you'd like**

I would like to customize the scrollbar by changing it's color according to the background of the webpage (All Pages).

**Are you willing to contribute to this issue?** [Yes/No]

`Yes`

**Additional context**

**Before**

![Screenshot_1](https://user-images.githubusercontent.com/61618767/113327109-2b5e8b00-9338-11eb-93cf-f9b2ced7d37c.png)

**After**
![Screenshot_2](https://user-images.githubusercontent.com/61618767/113327170-403b1e80-9338-11eb-992b-2aa6bf79c6b9.png)

As per your suggestion I can change the width/color of the scrollbar as well.

Kindly assign me this issue under GSSoC'21

**Comment by maneprajakta** [comment]
@Saatvik21 Good catch.
A Same color scroll bar for all pages would work. Go through [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) once it will help.
