### ISSUE TITLE
Can I contribute an Android APK of your site

### ISSUE THREAD

**Issue by MrDevLovePer** [Praful932/Kitabe#170]
Hello,
@MrDevLovePer here. I would like to contribute an Android APK of this site.

**Comment by Praful932** [comment]
Please follow the template :)
Also we don't think that is required
Check out [up-for-grab issues](https://github.com/Praful932/Kitabe/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee) or the [starter guide](https://github.com/Praful932/Kitabe/discussions/42)
