### ISSUE TITLE
Live application in the readme to open in a new tab 

### ISSUE THREAD

**Issue by akshay1027** [Praful932/Kitabe#176]
**Is your feature request related to a problem? Please describe.**
Live application in the readme to open in a new tab so that it is easier for the user to navigate to GitHub codebase.

**Are you willing to contribute to this issue?** [Yes]

**Comment by maneprajakta** [comment]
@akshay1027 follow the issue template for creating an issue.

**Comment by akshay1027** [comment]
Sorry!I found that we cant do this on Github! here is the link to that: mojombo/github-flavored-markdown#28
so i will close this issue
