### ISSUE TITLE
Improve footer UI

### ISSUE THREAD

**Issue by akshay1027** [Praful932/Kitabe#177]
**Is your feature request related to a problem? Please describe.**
Improvements we can add to Footer are :
1)Find us with logo
2)Call us with logo
3)Mail us with logo
4)Website logo
5)What this website is about
6)Follow us
-Instagram link with logo
-LinkedIn link with logo
-Twitter link with logo
-etc
7)Useful links
-Home
-Services
-About Us
-Contact Us etc
8)Subscribe
-Email address
9)Copyrights
10) All the above with responsive UI

**Are you willing to contribute to this issue?** [Yes]

**Comment by maneprajakta** [comment]
We don't feel need for this
