### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by vedantipawar** [Praful932/Kitabe#18]
Hey! I loved your project. The idea of using ratings was good too. But wont the existing books over shadow the recently published books due to fewer ratings. For example if I liked a particular book, I give it a 5-star rating but because there is only one review it wont be suggested to more people right? Because other books that are good would be having 5 stars and more number of reviews too. Not sure but if we use feature extraction from ML you can make the system even more accurate. Just a suggestion not an expert.

**Comment by Praful932** [comment]
Hi @vedantipawar, We are using the goodbooks dataset for model building. As mentioned in the Readme specifically in this [part](https://github.com/Praful932/Kitabe#model-exploration-), we are using a similarity measure on **books** on the basis of feature extracted from an already rated user-item dataset and also on the book title as well as the author. Currently there is no provision of recommending books based on another user's rated books. However its possible to use an user-user similiarity metric to recommend books, that would suit the case you mentioned possibly in a future release :)

If you would like to propose this method, feel free to discuss and then open a PR.

Regards,
Praful

**Comment by Praful932** [comment]
@vedantipawar Does this solve your issue?

**Comment by vedantipawar** [comment]
Yes, it solved my issue. Thankyou.
