### ISSUE TITLE
Adding "About" section and Resizing banner images

### ISSUE THREAD

**Issue by Greeshma2903** [Praful932/Kitabe#185]
**Is your feature request related to a problem? Please describe.**
Users might not exactly understand what the site is about. Also, when the site loads, the banner image covers the 3/4th of the viewport. 

**Describe the solution you'd like**
1. Adding an **About** section on the Home page will help users understand what the website does/ is.
2. Resizing the height of banner images, to direct the user's attention to feature sections.
 

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
Alternatively, we can add a separate **About** page (as and when required), which describes the site's features.

**Comment by Greeshma2903** [comment]
I have designed the same the  UI here: https://www.figma.com/file/quY3GKiD5RgWhsJAg2PKyE/?node-id=68%3A18


PS: I can design the UI for a separate **About** section if needed. But I am not sure if I can code the same, and will need some guidance.😅

**Comment by maneprajakta** [comment]
@Greeshma2903 
1.For the about us section a `welcome banner` in the carousel section which should come first is what we think would look great :rocket: .
2.For resizing go for what you feel will look appropriate.
Also for making banner, you can use [this](https://www.canva.com/)  maintain theme of website and also the font style.

**Comment by Greeshma2903** [comment]
Great! I Will work on it. 

Regarding the content, should I use continue with the same I used in the UI prototype? @maneprajakta

**Comment by ambivert-sam** [comment]
Hey, @Greeshma2903 can I work on this issue?

**Comment by Greeshma2903** [comment]
> Hey, @Greeshma2903 can I work on this issue?
Hello @ambivert-sam, guess you got confused, I am not the project maintainer😅
Regarding this issue, since it already assigned, you can look up the unassigned issues and go through [this](https://github.com/Praful932/Kitabe/discussions/42#discussion-3255567) as well. All the best👍👍

**Comment by Praful932** [comment]
@Greeshma2903 Looks nice 👍, Make the wordings same as the Repo description, make `Kitabe` italic  & bold and remove the bracket part. Move from - Simply to new line.

**Comment by Greeshma2903** [comment]
> @Greeshma2903 Looks nice 👍, Make the wordings same as the Repo description, make `Kitabe` italic & bold and remove the bracket part. Move from - Simply to new line.

Okay👍

**Comment by Greeshma2903** [comment]
Can I use the <picture> tag to source different images for smaller screens and larger screens?

![image](https://user-images.githubusercontent.com/70336930/114835172-eb46e000-9dee-11eb-85f9-1ec2d0e49f91.png)
