### ISSUE TITLE
Newsletter Subscription in Footer Section 

### ISSUE THREAD

**Issue by kumar-tushar** [Praful932/Kitabe#186]
There must be a weekly or monthly NEWSLETTER subscription for the user where they can enter their email and submit it.

THIS IS THE MOST REQUIRED FEATURE FOR THESE TYPES OF WEBSITES.

The Users will get emails related to popular or trending books.

If required then social links Insta, FB, LinkedIn, Twitter must be present.

@Praful932 I am excited to work on this new feature.

**Comment by Praful932** [comment]
Hi @kumar-tushar Thanks for your interest, but we wouldn't be needing this, there have been similar issues in the past, check out the discussion [here](https://github.com/Praful932/Kitabe/issues/45#issuecomment-794979602).
Meanwhile you can check out [up-for-grab issues](https://github.com/Praful932/Kitabe/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee) or the [starter guide](https://github.com/Praful932/Kitabe/discussions/42).
Also please follow the issue template next time you create an issue :)

Regards, 
Praful
