### ISSUE TITLE
addition in contributing.md

### ISSUE THREAD

**Issue by khareyash05** [Praful932/Kitabe#187]
Hi! I would like to add the following in contributing.md-
Difference between GIT and GITHUB
How to clone,fork repository
How to create a branch and then use git push to push to repo
Create a PR
Squash commits in a single issue into one
Updating the forked and local repo as the updations are made in the upstream

**Comment by Praful932** [comment]
Hi @khareyash05  Thanks for your interest, but we wouldn't be needing this, We believe we already have it covered in the starter guide.
Meanwhile you can check out [up-for-grab issues](https://github.com/Praful932/Kitabe/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee) or the [starter guide](https://github.com/Praful932/Kitabe/discussions/42).
Also please follow the issue template next time you create an issue :)

Regards, 
Praful
