### ISSUE TITLE
Using NLP to detect customer review

### ISSUE THREAD

**Issue by ParthSingh0506** [Praful932/Kitabe#188]
->Using NLP to detect customer review

->The basic idea is that our ML model will able to tell whether the review given by person is negative or positive by using the 
  NLP . 

**Are you willing to contribute to this issue?** [Yes/No]
->Yes

**Comment by ParthSingh0506** [comment]
@Praful932  kindly assign me this issue

**Comment by Praful932** [comment]
Hi @ParthSingh0506 Appreciate your interest in the project, but we don't really have a review section in the application.
You can check out [up-for-grab issues](https://github.com/Praful932/Kitabe/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee) or the [starter guide](https://github.com/Praful932/Kitabe/discussions/42).
Also please follow the issue template next time you create an issue :)

Regards,
Praful
