### ISSUE TITLE
Improve Footer

### ISSUE THREAD

**Issue by akshay1027** [Praful932/Kitabe#189]
**Describe the bug**
Improvements that can be made in footer are:
1)Find us
2)Call us 
3)Mail us 
4)Website logo
5)What this website is about
6)Follow us
-Instagram link with logo
-LinkedIn link with logo
-Twitter link with logo
-etc
7)Useful links
-Home
-Services
-About Us
-Contact Us etc
8)Subscribe
-Email address
9)Copyrights
10) All the above with responsive UI

**Comment by akshay1027** [comment]
I would like to work on this!
@maneprajakta @Praful932

**Comment by maneprajakta** [comment]
@akshay1027 thanks for showing interest.
But we don't need this feature meanwhile checkout other issues.
