### ISSUE TITLE
Navbar on smaller devices

### ISSUE THREAD

**Issue by satcasm** [Praful932/Kitabe#193]
**Is your feature request related to a problem? Please describe.**
The navbar for smaller devices is all messed up and also I noticed the elements of the navbar are not responsive with the screen size.

**Describe the solution you'd like**
Making the navbar elements responsive with the screen size and also improving the alignment of navbar for smaller devices.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
Haven't considered any alternatives.

**Additional context**
![image](https://user-images.githubusercontent.com/56315878/114309255-39649680-9b04-11eb-87e9-349e10f69575.png)

**Comment by maneprajakta** [comment]
@satcasm Follow issue template for creating an issue.
Check #185 this is what we expect in an issue.

**Comment by satcasm** [comment]
My apologies, should I close this issue and create a new one?

**Comment by maneprajakta** [comment]
You can edit this issue

**Comment by satcasm** [comment]
Ok sure, will do that.

**Comment by satcasm** [comment]
@maneprajakta made the required changes.

**Comment by maneprajakta** [comment]
@satcasm Go ahead then.

**Comment by maneprajakta** [comment]
@Praful932 I think we should close this issue. We need to first go for a new design of nav-bar as we had decided.

**Comment by Praful932** [comment]
Agree

> @Praful932 I think we should close this issue. We need to first go for a new design of nav-bar as we had decided.
