### ISSUE TITLE
Login and Signup Page Layout

### ISSUE THREAD

**Issue by maneprajakta** [Praful932/Kitabe#194]
**Describe the bug**
- For large screen :
   In `login in` page When a user enters wrong password space between buttons increases and also form content goes out of div.
- For small screen :
  On `login in` ,`sign up` page form border is not aligned properly also when a user enters wrong password  it's messed up same 
   as in large screen.

**To Reproduce**
- First bug:
1. Go to 'login'
2. Enter user name and wrong password
3. See error
- Second bug:
1. Open sigin & signup page on mobile.

**Expected behavior**
- For large screen: 
  Space btw buttons should not increase the form border should remain inside div
- For small screen:
  It should be responsive.

**Screenshots**
- Large screen:

![Screenshot from 2021-04-11 21-52-16](https://user-images.githubusercontent.com/57425995/114312447-5606cb80-9b10-11eb-8c54-9478a1db0d1b.png)

- Small screen:
- `login page`
![WhatsApp Image 2021-04-11 at 9 27 18 PM (1)](https://user-images.githubusercontent.com/57425995/114312721-49cf3e00-9b11-11eb-8084-de61940889a5.jpeg)

-`sign up page`
![WhatsApp Image 2021-04-11 at 9 27 18 PM (3)](https://user-images.githubusercontent.com/57425995/114312734-53f13c80-9b11-11eb-86d9-6790bcc4cfd7.jpeg)

- `login with wrong password`
![WhatsApp Image 2021-04-11 at 9 27 17 PM (1)](https://user-images.githubusercontent.com/57425995/114312753-610e2b80-9b11-11eb-84f2-1ce02e754345.jpeg)

**Are you willing to contribute to this issue?** [Yes/No]
No
**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome

**Comment by satcasm** [comment]
Hey @maneprajakta I can work  on this issue. Can you assign it to me?

**Comment by maneprajakta** [comment]
@satcasm Go ahead :rocket: 
Once read [starter Guide](https://github.com/Praful932/Kitabe/discussions/42) it will help.

**Comment by satcasm** [comment]
Hey @maneprajakta , for larger screens is it good or should I make some more changes?
![image](https://user-images.githubusercontent.com/56315878/114317438-bc4a1900-9b25-11eb-8e6d-ed7cf7719719.png)
Had to make the buttons inline so that when the error message pops up the elements don't go outside the div.

**Comment by satcasm** [comment]
For smaller Screens:
![image](https://user-images.githubusercontent.com/56315878/114317658-cfa9b400-9b26-11eb-963b-1eddd7eff2b6.png)
![image](https://user-images.githubusercontent.com/56315878/114317807-8017b800-9b27-11eb-82da-ab15e34d2648.png)

**Comment by maneprajakta** [comment]
@satcasm we don't want the button to be placed side by side.`sign in` button should be above `sign in with google button` and both buttons should be centrally aligned.

**Comment by satcasm** [comment]
Hey @maneprajakta apologies for late response.
![image](https://user-images.githubusercontent.com/56315878/115065994-85507a80-9f0c-11eb-837e-7a7ac24bef17.png)
Is this fine for ```large screen```?
![image](https://user-images.githubusercontent.com/56315878/115066558-5555a700-9f0d-11eb-8eb7-f12fa67f9278.png)
![image](https://user-images.githubusercontent.com/56315878/115066742-92ba3480-9f0d-11eb-943e-6d388dae146b.png)
For ```small screen```?

**Comment by maneprajakta** [comment]
@satcasm looks great me just check once for the 360x640 px screen also is everything approriate.
