### ISSUE TITLE
The margin between cards can be increased

### ISSUE THREAD

**Issue by akshay1027** [Praful932/Kitabe#195]
**Describe the bug**
The margin between cards can be increased to make a better UI.

**Screenshots**

![2021-04-12_LI](https://user-images.githubusercontent.com/65683151/114317823-94f44b80-9b27-11eb-938c-9bca361555b7.jpg)

**Are you willing to contribute to this issue?** [Yes]

**Comment by maneprajakta** [comment]
@akshay1027 cards are also of uneven size can you fix that too.

**Comment by akshay1027** [comment]
Sure!

**Comment by Praful932** [comment]
Imo margin looks fine, only issue is uneven card size
