### ISSUE TITLE
Want to Change Navbar design 

### ISSUE THREAD

**Issue by vedant-jain03** [Praful932/Kitabe#196]
**Is your feature request related to a problem? Please describe.**

* I want to Change  the style of Navbar as it don't have any good hover effect and the icons are also very big.

**Describe the solution you'd like**

I want to edit the navbar.
I will align items in much good way.
I will also provide you with cool hovers effect
I will also give 100vh to welcome image so that it will make a good look.

**Are you willing to contribute to this issue?** [Yes]

![bandicam 2021-04-12 13-58-11-288](https://user-images.githubusercontent.com/76901313/114365120-c3aa0a80-9b97-11eb-89f3-433042eafca7.jpg)

**Comment by vedant-jain03** [comment]
@maneprajakta Please assign me the issue if valid

**Comment by Praful932** [comment]
@vedant-jain03 There's an ongoing PR #180 for the same, Could you be specific/show some mockups of how you expect to make it better?

**Comment by vedant-jain03** [comment]
I was thinking to Change
* Height of Navbar as it occupies much space.
* Icons and its respective names : I am thinking to remove icons as it occupies more space and show only Text , it will make give professional look.
* I will also make banner and navbar full the size of the window so that it look more like professional website.
* I will make a good hovering effect in Navbar.
* Will also give more space to search bar.

If any think more you want or to recommend I will make you sure to provide that
If you think it is valid issue Please assign me

**Comment by Praful932** [comment]
I think we would like to keep the icons.
As for the other changes I don't think we would be needing that @maneprajakta Wdyt
