### ISSUE TITLE
Show password feature in login/signup

### ISSUE THREAD

**Issue by arpit456jain** [Praful932/Kitabe#198]
**Is your feature request related to a problem? Please describe.**
There is no show password button some time when any wrong key is pressed if this show password is not present then user have to remove its whole password 

**Describe the solution you'd like**
I would like to add a show password feature to login and sign up

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**

**Additional context**

**Comment by Praful932** [comment]
Follow the issue template.

**Comment by arpit456jain** [comment]
> Follow the issue template.

done

**Comment by Praful932** [comment]
We have a priority issue - #194 which needs to be fixed before anything is added to login/signup, so I'll be closing this issue(since its an enhancement) for now, will reopen after that is fixed.
Thanks

**Comment by arpit456jain** [comment]
Ok no problem but please merge my pr for 404 page
