### ISSUE TITLE
Banner + Navbar height

### ISSUE THREAD

**Issue by vedant-jain03** [Praful932/Kitabe#199]
**Describe the bug**

I think the banner + navbar should contain height of 100vh total

**Before**
![bandicam 2021-04-12 13-58-11-288](https://user-images.githubusercontent.com/76901313/114498396-a3368a80-9c41-11eb-8ccf-faf5441bdfd8.jpg)

**After**
![bandicam 2021-04-13 10-17-18-511](https://user-images.githubusercontent.com/76901313/114498399-a467b780-9c41-11eb-94f7-5458ebc725b7.jpg)

**Comment by vedant-jain03** [comment]
@Praful932 
If valid issue please assign me

**Comment by maneprajakta** [comment]
@vedant-jain03 we don't feel the need for this.
