### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by vedant-jain03** [Praful932/Kitabe#200]
**Is your feature request related to a problem? Please describe.**

I wanted to add night mode feature into this website.

**Describe the solution you'd like**

* Their will be button of checkbox type when user click it, theme will change to night theme.

**Are you willing to contribute to this issue?** [Yes/No]
* yes

**Comment by vedant-jain03** [comment]
@Praful932 if valid please assign.

**Comment by maneprajakta** [comment]
@vedant-jain03 already we have an issue check #41
