### ISSUE TITLE
Readme file enhancement

### ISSUE THREAD

**Issue by anirudhsai20** [Praful932/Kitabe#202]
The Readme file can be enhanced by adding a list of all the Open Source programs in which this project has been listed in.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by Praful932** [comment]
@anirudhsai20 We don't think there is a need for that :)
Checkout the starter [guide](https://github.com/Praful932/Kitabe/discussions/42).
Thanks
