### ISSUE TITLE
Add social sites icon to the left of window

### ISSUE THREAD

**Issue by ShrutiOmer** [Praful932/Kitabe#204]
**Is your feature request related to a problem? Please describe.**
Want to add social app icons to the left ,Something like this

![icons](https://user-images.githubusercontent.com/75009990/114841981-0a953b80-9df6-11eb-8724-ce4eaa38551a.png)

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Comment by Praful932** [comment]
I don't think we would be needing this. :)
Thanks for your interest, check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42).
