### ISSUE TITLE
Website is not responsive 

### ISSUE THREAD

**Issue by CMELAKKIA** [Praful932/Kitabe#207]
---
name: Feature request
about: Responsiveness
title: ''Making the website responsive for all devices"
labels: ''GSSOC'21"
assignees: ''CMELAKKIA"

---

**Is your feature request related to a problem? Please describe.**
The current website needs to be responsive. 

**Describe the solution you'd like**
It can re-dimension it according the the device used.

**Are you willing to contribute to this issue?** 
YES

**Comment by maneprajakta** [comment]
@CMELAKKIA follow the issue template for creating an issue.

**Comment by CMELAKKIA** [comment]
> @CMELAKKIA follow the issue template for creating an issue.

Yeah, done.

**Comment by maneprajakta** [comment]
@CMELAKKIA Thanks for showing interest.
We have some high-priority issues that we believe in solving first.
We don't think this enhancement is needed now.
