### ISSUE TITLE
add DARK mode

### ISSUE THREAD

**Issue by codebuzzer01** [Praful932/Kitabe#211]
**Is your feature request related to a problem? Please describe.**
There is no dark mode as users prefer dark mode more.

**Describe the solution you'd like**
I would like to add a toggle button for dark mode which user if want to can turn on and off

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Comment by codebuzzer01** [comment]
@maneprajakta shall I work on this?

**Comment by Praful932** [comment]
Check out #41 :)
