### ISSUE TITLE
Navbar look

### ISSUE THREAD

**Issue by RuchiGitHu** [Praful932/Kitabe#212]
**Is your feature request related to a problem? Please describe.**
Whenever I see website the navbar buttons look so congested and because of that the extra space can be seen in the middle of navbar. 
The logo of website also looks too small as compare to other things in website...

**Describe the solution you'd like**
I want to put some space in between navbar buttons. Wanted to increase size of logo so that it can catch eyes directly whenever anyone load website.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Additional context**
Search bar can be placed when we maintain the space between navbar buttons.

![image](https://user-images.githubusercontent.com/71754179/115906005-9299c780-a42c-11eb-8971-189cd9073b35.png)
![image](https://user-images.githubusercontent.com/71754179/115906130-bf4ddf00-a42c-11eb-8d3f-401f9f48811b.png)

**Comment by RuchiGitHu** [comment]
Please assign this issue to me under gssoc21.

**Comment by maneprajakta** [comment]
@RuchiGitHu Thanks for showing interest.
We are going to change the nav-bar design under a new issue. We don't need this enhancement now.
