### ISSUE TITLE
Add github action to auto assign GSSOC21 tag to all the issues created and prs opened during this GSSOC period

### ISSUE THREAD

**Issue by AB-san** [Praful932/Kitabe#214]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/71064674/115962964-51dca400-a53b-11eb-9be3-1c9cfa07184d.png)

i noticed @maneprajakta adding so many tags each and every time a new issue is created.

**Describe the solution you'd like**
1)I would like to add github action that will auto assign GSSOC21 tag to all the issues created in this GSSOC period.
2) Add github action tht will auto assign GSSOC21 tag to all the opened prs.

This will save the precious time of our mentors to some extent.

**Are you willing to contribute to this issue?** [Yes]

**Describe alternatives you've considered**

**Additional context**

**Comment by Praful932** [comment]
Thank you for your interest in the project @AB-san :)
We don't think we would need a GH for auto-adding a single tag, a bit overkill :)
