### ISSUE TITLE
Confirmation before logout

### ISSUE THREAD

**Issue by arpit456jain** [Praful932/Kitabe#215]
**Is your feature request related to a problem? Please describe.**
Some times it is possible for the user to click on logout by mistake 

**Describe the solution you'd like**
There should be a confirmation alert before logout it will be look something like this.
<img width="361" alt="sweet alert" src="https://user-images.githubusercontent.com/55352601/115963697-2ad3a180-a53e-11eb-9757-4433c39ae7d4.png">

**Are you willing to contribute to this issue?** [Yes/No]
YES

**Comment by Praful932** [comment]
Thanks for your interest, We don't think we currently need this :)
