### ISSUE TITLE
Add github action tht 'll send auto request to the mentors to review pr

### ISSUE THREAD

**Issue by AB-san** [Praful932/Kitabe#216]
**Is your feature request related to a problem? Please describe.**
After the contributors push their code , the mentors will be automatically be assigned to review the changes

**Describe the solution you'd like**
Add a github action that will send auto request to the mentors to kindly review the opened pr

**Are you willing to contribute to this issue?** [Yes]

**Describe alternatives you've considered**

**Additional context**

**Comment by Praful932** [comment]
Thanks for your interest, Don't think we would be needing this atm :)
