### ISSUE TITLE
Add a github action to auto-reply after a pr is merged

### ISSUE THREAD

**Issue by AB-san** [Praful932/Kitabe#217]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add a github action to auto-reply after a pr is merged successfully , message like - Thank you @username for your contribution . Looking forward for more such amazing contribution " Or any other as per the mentor's wish

**Are you willing to contribute to this issue?** [Yes]

**Describe alternatives you've considered**

**Additional context**

**Comment by Praful932** [comment]
Don't think we would be needing this :)
