### ISSUE TITLE
Add github action to auto-reply when a new pr is opened 

### ISSUE THREAD

**Issue by AB-san** [Praful932/Kitabe#218]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Add github action to send auto-message to the contributors whenever they send a new pr
message for example - "We got your code , @username please wait for our team to review it."
or any other message as per the mentor's wish

**Are you willing to contribute to this issue?** [Yes]

**Describe alternatives you've considered**

**Additional context**

**Comment by Praful932** [comment]
@AB-san GH Notifications seem handy for the same, seems a bit overkill :)
