### ISSUE TITLE
Popular among us Book card

### ISSUE THREAD

**Issue by maneprajakta** [Praful932/Kitabe#22]
**Popular among us Book card**
The current book card does not put a limit on the book title and book author text displayed.
so, when the book title name, author name exceed the line limit that can be displayed on the card it leads to overflow and also overlaps with the buttons. 

**To Reproduce**
Steps to reproduce the behavior :
1. Go to 'home page'
2. Scroll down to the 'popular among us section'
4. See book cards

**Expected behavior**
Author name and Book title should fix in the card without overflow and overlap.

**Screenshots**
![Screenshot from 2020-12-19 11-54-57](https://user-images.githubusercontent.com/57425995/102682923-20ea0c80-41f3-11eb-93c7-3c4dd23b081a.png)
![Screenshot from 2020-12-19 12-09-28](https://user-images.githubusercontent.com/57425995/102682926-23e4fd00-41f3-11eb-8584-a999956e6cc3.png)

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser:Chrome
 - Version :86.0.4240.198 (Official Build)

**Comment by Praful932** [comment]
@maneprajakta #21 Was this only for Author names?

**Comment by maneprajakta** [comment]
@Praful932 yes

**Comment by Praful932** [comment]
Shall I make a PR with this - `{{ value|truncatechars:7 }}` fix?

**Comment by maneprajakta** [comment]
Yes no issue .
