### ISSUE TITLE
Want to make some changes to login page

### ISSUE THREAD

**Issue by kanisshka** [Praful932/Kitabe#220]
**Is your feature request related to a problem? Please describe.**
No, it's a suggestion.

**Describe the solution you'd like**
I want to change css for this.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Additional context**
![image](https://user-images.githubusercontent.com/76627599/116428226-5a4a1d00-a862-11eb-847f-dafc5a50f94f.png)

**Comment by Praful932** [comment]
Hi @kanisshka Could you elaborate and update the PR Description? Something like this #30 
Preferrably Some answers to questions like What do you intend to make it into?
What & Which css you want to change?

**Comment by kanisshka** [comment]
> Hi @kanisshka Could you elaborate and update the PR Description? Something like this #30
> Preferrably Some answers to questions like What do you intend to make it into?
> What & Which css you want to change?

Just like first, I want to make an 'OR' line between sign in and sign in with google.
secondly wanted to change some layout or some appearance of this page.

**Comment by Praful932** [comment]
I don't think we need an OR rn, layout and appearance as in? Could you show an example

**Comment by kanisshka** [comment]
> I don't think we need an OR rn, layout and appearance as in? Could you show an example

![image](https://user-images.githubusercontent.com/76627599/116594538-f433c780-a93f-11eb-9f95-d77a083b2e6e.png)
Like this....

**Comment by Praful932** [comment]
A wireframe perhaps? Like [this](https://www.figma.com/file/4TLJEYoQa2yms4JniLwThz/mockup1?node-id=0%3A1)
What you intend to do? So we know if we want this enhancement or not

**Comment by kanisshka** [comment]
I think maybe I'm not able to make you understand.
so thank you I try somewhere later
