### ISSUE TITLE
Search bar not working?

### ISSUE THREAD

**Issue by AmrutaKoshe** [Praful932/Kitabe#223]
**Describe the bug**
After typing and selecting a book from the search bar, it doesn't display that book. Even pressing enter doesn't work.

**To Reproduce**
1. Go to https://kitabe-app.herokuapp.com/explore_books/
2. Click on search bar
3. Type any book.

**Expected behavior**
A page displaying that book should appear, or if enter is pressed, all the books containing the searched word must appear.

**Screenshots**
![Animation](https://user-images.githubusercontent.com/59871941/116963351-3c4b4500-acc6-11eb-805b-17e2c8bacb0c.gif)

**Are you willing to contribute to this issue?** [Yes]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows
 - Browser [e.g. chrome, safari] - chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maneprajakta** [comment]
@Praful932 it doesn't work even at my end for all pages but when I inspect the page and change it to mobile view it works fine If you could check at your side.

**Comment by Praful932** [comment]
Hmm, After entering the full name, sometimes it opens the book modal sometimes it doesn't

**Comment by maneprajakta** [comment]
@AmrutaKoshe you can work on this issue. Go ahead.

**Comment by maneprajakta** [comment]
@AmrutaKoshe where you able to figure out the problem.

**Comment by AmrutaKoshe** [comment]
> @AmrutaKoshe were you able to figure out the problem.

Hi sorry I had my college practicals. I will work on it today

**Comment by maneprajakta** [comment]
No issue!

**Comment by Praful932** [comment]
Fixed
![image](https://user-images.githubusercontent.com/45713796/126892976-0a27534f-5e4f-4ffa-b18a-398b0c13ab37.png)
