### ISSUE TITLE
Enhancing features of home and explore page

### ISSUE THREAD

**Issue by PranavChauhan22** [Praful932/Kitabe#225]
Is your feature request related to a problem? Please describe.
It's not an issue.Actually when we lands on home and explore page,the page looks somewhat rough as there are less animations and transitions.

Describe the solution you'd like
I will add something like rotating globe or book opening and closing animations with less opacity in banner of home page and will add scroll animations in explore page.

Are you willing to contribute to this issue?
Yes

Describe alternatives you've considered
N/A

Additional context

https://pranavchauhan22.github.io/PranavBlog/pranavblog.html

You can go through the landing page of my blog,want to add the globe type (as site is concerned about books i will add book animation) in home page.

**Comment by maneprajakta** [comment]
@PranavChauhan22 could you follow the issue template and also provide an example there like in what way you want to make it dynamic.

**Comment by PranavChauhan22** [comment]
Is your feature request related to a problem? Please describe.
It's not an issue.Actually when we lands on home and explore page,the page looks somewhat rough as there are less animations and transitions.

Describe the solution you'd like
I will add something like rotating globe or book opening and closing animations with less opacity in banner of home page and will add scroll animations in explore page.

Are you willing to contribute to this issue?
Yes

Describe alternatives you've considered
--

Additional context

https://pranavchauhan22.github.io/PranavBlog/pranavblog.html

You can go through the landing page of my blog,want to add the globe type (as site is concerned about books i will add book animation) in home page.

**Comment by PranavChauhan22** [comment]
should i proceed for it,eagerly waiting for reply?

**Comment by maneprajakta** [comment]
@PranavChauhan22 liked the interactive resume :) it's pretty cool.
Could you provide a mock-up where exactly you wish to add animation?

**Comment by PranavChauhan22** [comment]
https://user-images.githubusercontent.com/83133554/117934461-55846f00-b320-11eb-9172-c94806620563.mp4

This is what i did in the banner section of website.
-- Removed the carousel
-- changed the background color
-- added some animations in place of carousel

**Comment by maneprajakta** [comment]
@PranavChauhan22 thanks for the interest.
But we don't think we need such feature on the website.
