### ISSUE TITLE
Navbar(sticky)

### ISSUE THREAD

**Issue by SamikshaSankar** [Praful932/Kitabe#228]
**Is your feature request related to a problem? Please describe.**
Navbar is not sticky

**Describe the solution you'd like**
I want to make sticky effect on navbar.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
N/A

**Comment by Praful932** [comment]
Hi @SamikshaSankar Thanks for your interest :), There was already an issue made for the same #44
