### ISSUE TITLE
Improper positioning

### ISSUE THREAD

**Issue by sonaljain067** [Praful932/Kitabe#229]
**Is your feature request related to a problem? Please describe.**
On the main page, the tiles are in quite an improper position. 

**Describe the solution you'd like**
Aligning all tiles to the same baseline.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Additional context**
![Screenshot from 2021-05-11 16-32-40](https://user-images.githubusercontent.com/52230497/117806213-9f654a80-b277-11eb-8820-1fa640300374.png)

**Comment by maneprajakta** [comment]
@Praful932 is this problem going to be solved by #48

**Comment by Praful932** [comment]
> @Praful932 is this problem going to be solved by #48

Nope we can take this here

**Comment by sonaljain067** [comment]
Can I work on this issue?

**Comment by Praful932** [comment]
Yea go ahead
