### ISSUE TITLE
QA : Add formatter and linter 

### ISSUE THREAD

**Issue by Aryamanz29** [Praful932/Kitabe#234]
- Need a workflow that ensures every contributor should follow the [PEP-8](https://www.python.org/dev/peps/pep-0008/) style guide for python code.
- We can use `flake8` for linting and `Black` for formatting source code.
- Also this workflow runs on every PR which ensures the code follows  [PEP-8](https://www.python.org/dev/peps/pep-0008/) standard or not.

**Comment by Aryamanz29** [comment]
@maneprajakta  @Praful932  I would like to work on this

**Comment by maneprajakta** [comment]
@Aryamanz29 we already have a workflow for the project. We did not need these additions to it.
