### ISSUE TITLE
Different heights of button

### ISSUE THREAD

**Issue by sonaljain067** [Praful932/Kitabe#235]
**Is your feature request related to a problem? Please describe.**
On explore page, the buttons are of different heights.

**Describe the solution you'd like**
Making the heights of the button uniform.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Additional context**
![Screenshot from 2021-05-16 12-42-33](https://user-images.githubusercontent.com/52230497/118388855-86c4ae00-b644-11eb-8be5-37d3d606122c.png)

**Comment by maneprajakta** [comment]
@sonaljain067 Go ahead with this!
