### ISSUE TITLE
Adding custom scrollbar in firefox

### ISSUE THREAD

**Issue by Alenjojo** [Praful932/Kitabe#237]
**Describe the bug**
the scrollbar of chrome has been customized but it hasn't effected firefox cuz it uses different syntax for it
**To Reproduce**
1. Go to 'firefox'
2. Click on 'website link'
3. Scroll down to 'and you can see the default scrollbar in it'

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/51394913/118831732-a3c7de00-b8dd-11eb-8420-2ce0fe1b3cca.PNG)

**Are you willing to contribute to this issue?** [Yes/No]
Yes
**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [unknown]

**Additional context**
i'm a gssoc participate and if you could assign me i'll resolve the issue, there isn't enough resources for firefox, but i'll try my best

**Comment by maneprajakta** [comment]
@Praful932 what you say about this?

**Comment by Praful932** [comment]
> @Praful932 what you say about this?

Sounds as a resonable issue

**Comment by Alenjojo** [comment]
i know u asked me to do exactly as seen from chrome, but there are some limitation for Firefox. Then only syntax that it has to make it thin and change color. I'll be putting two images you tell you which ones better. @Praful932 
![thin](https://user-images.githubusercontent.com/51394913/119133012-072a4b00-ba59-11eb-8829-85bbd93fbf18.PNG)
![5px](https://user-images.githubusercontent.com/51394913/119133024-0abdd200-ba59-11eb-965d-a52b0318e9dc.PNG)

**Comment by Praful932** [comment]
@Alenjojo Alright the one with the same width in chrome and same color works for us

**Comment by Alenjojo** [comment]
Thats what i'm trying to say, there isn't enough syntax in firefox to make in look exactly as of chrome. I can only make it thin and change color

**Comment by Praful932** [comment]
Alright the first one works then
