### ISSUE TITLE
Redesign login text box for better user experience

### ISSUE THREAD

**Issue by Alenjojo** [Praful932/Kitabe#238]
**Is your feature request related to a problem? Please describe.**
The current text box is the default has don't match the current user experience

**Describe the solution you'd like**
Will try adding some better CSS to make it look pretty

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Additional context**
As you can see below the text box is giving an outline and the forgot password isn't properly aligned.
![Screenshot (9)](https://user-images.githubusercontent.com/51394913/118848979-e3e28d00-b8ec-11eb-9666-44777a96f237.png)

**Comment by maneprajakta** [comment]
@Alenjojo sure go ahead!

**Comment by ambivert-sam** [comment]
Participant of gssoc'21 and willing to contribute to this issue, can you please assign me?

**Comment by Praful932** [comment]
Hi @ambivert-sam This is already assigned, check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42) :)

**Comment by Praful932** [comment]
Closing this as no longer in priority
