### ISSUE TITLE
After refereshing the info remains

### ISSUE THREAD

**Issue by Alenjojo** [Praful932/Kitabe#243]
**Describe the bug**
In the login page when we type down the wrong credentials and its says username and password not found. So even after we refresh the page except the password everything stays put. So it makes a bit confuse for the user.
**To Reproduce**
1. Go to 'login page'
2. Click on 'login in'
3. Scroll down to 'refresh the page'

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/51394913/119255023-1b945200-bbd7-11eb-9244-84a2afdf9945.PNG)

**Are you willing to contribute to this issue?** [Yes/No]

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]

**Additional context**

**Comment by maneprajakta** [comment]
@Alenjojo after refreshing the page username doesn't stay up
