### ISSUE TITLE
Incorrect display in a range

### ISSUE THREAD

**Issue by sonaljain067** [Praful932/Kitabe#244]
**Is your feature request related to a problem? Please describe.**
From 601 to 768 px, 
The logo moves right side 
Toggle button to the left side 
Also, the icons of the navbar don't look good in this range.

**Describe the solution you'd like**
Positioning the logo on the left side, toggle button to the right side, and removing the display of icons in this range. 

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Additional context**
![Screenshot from 2021-05-25 22-14-05](https://user-images.githubusercontent.com/52230497/119536895-2a316380-bda7-11eb-96b8-90ae8bf897af.png)

**Comment by Praful932** [comment]
Go ahead @sonaljain067 👍
