### ISSUE TITLE
The Navbar is disturbed in small screen sizes

### ISSUE THREAD

**Issue by AmeyaJain-25** [Praful932/Kitabe#247]
**Describe the bug**
In small screen sizes, the navbar is disturbed and the menu icon comes on another line

**To Reproduce**
1. Go to 'kitabe website'
2. Open in small screen width size

**Expected behavior**
The navbar should also properly aligned in small mobile screen sizes as like tab sizes.

**Screenshots**
![Screenshot from 2021-05-29 12-02-47](https://user-images.githubusercontent.com/66305085/120060968-7666f700-c078-11eb-8faf-1dc4023e5eb2.png)

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Additional context**
Please assign me this issue under GSSoC21'

**Comment by maneprajakta** [comment]
@AmeyaJain-25 can you specify the screen range?

**Comment by AmeyaJain-25** [comment]
> @AmeyaJain-25 can you specify the screen range?

355px and below

**Comment by maneprajakta** [comment]
@AmeyaJain-25 Go ahead. Read once [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) it would help.
