### ISSUE TITLE
Hovering effect on More Details button in explore section.

### ISSUE THREAD

**Issue by ishitakapoor26** [Praful932/Kitabe#249]
Description
Hovering effect is not there on More Details button in Explore Section.

To Reproduce
Go to 'kitabe website'
Open explore section.
Expected behavior
More Details button should change colour and border when pointer is placed over it.

Screenshots
![Capture](https://user-images.githubusercontent.com/78542333/120144520-ad1b4980-c1ff-11eb-8239-4ed64eae09ad.PNG)
Are you willing to contribute to this issue? [Yes/No]
Yes

Additional context
Please assign me this issue under GSSoC21'

**Comment by ishitakapoor26** [comment]
Pls assign this issue to me and review my pr #250 @varunkmr19 @ImgBotApp

**Comment by maneprajakta** [comment]
@ishitakapoor26 could you plz edit the Issue description it should be something like this #247. Then we can move forward.

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 could you plz edit the Issue description it should be something like this #247. Then we can move forward.

Reply: Yes

**Comment by maneprajakta** [comment]
@ishitakapoor26 `more details` button for all pages don't have a hovering effect on it. It would be great if you could put that for all pages.
Just add a text-shadow as hovering effect.Something like this would work.
`text-shadow: 0px 0px 6px white;
 color:white;`

**Comment by ishitakapoor26** [comment]
Ok I'll do

**Comment by ishitakapoor26** [comment]
@maneprajakta added hovering effect to all the buttons and text to all the pages. Pls review my pr.

**Comment by ishitakapoor26** [comment]
Pls merge it @maneprajakta

**Comment by ishitakapoor26** [comment]
@maneprajakta I've resolved all the changes. Now pls check
