### ISSUE TITLE
To create a fixed top navbar.

### ISSUE THREAD

**Issue by Simranjakhodia** [Praful932/Kitabe#257]
**Is your feature request related to a problem? Please describe.**
Yes. At present, while scrolling we see that navbar isn't fixed to the top

**Describe the solution you'd like**
The navigation bar will remain at the top while scrolling and it will  make the browsing even easier.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
Want to make changes in templates/mainapp/layout.html  to add a fixed navbar

**Comment by Praful932** [comment]
Hi @Simranjakhodia Thanks for your interest in the project :), There has been already an issue regarding that - #44
