### ISSUE TITLE
Recommendations based on what the user views

### ISSUE THREAD

**Issue by liperrino** [Praful932/Kitabe#261]
**Is your feature request related to a problem? Please describe.**
I would like to have suggestions based on what the user views too
**Describe the solution you'd like**
If a user clicks on a book of a particular gender(3 times) then next reload suggestions will be more based on that gender and the rest of genders on which he has clicked too.
**Are you willing to contribute to this issue?** 
Yes, But don't have the knowledge for that
**Describe alternatives you've considered**

**Additional context**
I would also like to know how you have obtained your train models in static folder.

**Comment by Praful932** [comment]
Hi @liperrino, Could you elaborate on what you mean by gender?
>book of a particular **_gender_**(3 times)
By any chance did you mean to say _genre_?

As for the train models, you can refer the [Notebook and Files section](https://github.com/Praful932/Kitabe#notebooks-and-files-) in the Readme particularly the Cleaning & Embedding Notebook from which the resulting embeddings are generated and the Tfidf Notebook From which the Tfidf Matrices are generated
