### ISSUE TITLE
Frontend Bug Fixes

### ISSUE THREAD

**Issue by Praful932** [Praful932/Kitabe#30]
**Describe the bug**
There are certain frontend bug fixes especially the **Rate this book** button after the last patch. All bugs are after a user signs in.

**Screenshots**

1. **Homepage** - Popular Among Users Section (Improper Button Size and Alignment)
![image](https://user-images.githubusercontent.com/45713796/107850560-48430b80-6e29-11eb-8796-a909ff3c1f0f.png)
2. **Your Read Section** (Improper Size, Alignment and Rating Validation)
![image](https://user-images.githubusercontent.com/45713796/107850614-b4257400-6e29-11eb-9a21-8019e8909e6d.png)

**Expected behavior**
1. All buttons should be fixed as when user is not logged in
![image](https://user-images.githubusercontent.com/45713796/107850663-0e263980-6e2a-11eb-80ea-672bd674dfdd.png)
2. For 3. Validation should be added after a book is rated, similar to below
![validation](https://user-images.githubusercontent.com/45713796/107850734-9e647e80-6e2a-11eb-9426-ed38ff40043c.gif)

**Definition of Done**
All sub-tasks are done and pass tests

**Comment by ranjal007** [comment]
@Praful932 Can I work on this issue

**Comment by Praful932** [comment]
Hi @ranjal007 Thanks for your interest in contributing to this project :) 
We are currently setting up the project for automated tests on PR, a bit more documentation and more enhancement issues. This setup will be ready in this week. I'll tag you again as soon as the internal changes are done

Thanks

**Comment by ranjal007** [comment]
@Praful932  Okay I will be waiting for the response.

**Comment by supzi-del** [comment]
Can I take this up?

**Comment by samfubuki** [comment]
Can I work on this issue?

**Comment by Vartika511** [comment]
Can I takes this issue??

**Comment by Praful932** [comment]
Hello! Thank you for your interest for contributing to this issue. We will be locking the conversations as we are currently undergoing some internal changes, after unlocking contibutors will be tagged to work on the issue
Thanks

**Comment by Praful932** [comment]
Let me know if you @ranjal007 would like to work on this, I'll assign once you acknowledge

**Comment by abhish3k-11** [comment]
I'd like to work on this. @Praful932 .

**Comment by Praful932** [comment]
@abhish3k-11 Go ahead!

**Comment by abhish3k-11** [comment]
@Praful932 the css is not working, so I'm going ahead and make some changes to resolve the same. Then I'll fix the frontend bugs. Is it okay?
<img width="960" alt="see" src="https://user-images.githubusercontent.com/67673898/110280635-280a0500-8001-11eb-973c-87e46ca6acf1.PNG">

**Comment by Praful932** [comment]
@abhish3k-11 It needs to be run on a server. Please follow the [Guide](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md) for setting up the Project

**Comment by abhish3k-11** [comment]
Oh yeah! Thanks for the help!!

**Comment by sahildotexe** [comment]
Can you please assign me to this issue?

**Comment by Praful932** [comment]
@sahildotexe Please read the [guidelines](https://github.com/Praful932/Kitabe/discussions/42) 🙂
Thanks

**Comment by simranbhalla3** [comment]
I am participant in GSSOC'21.Can you please assign this to me? @Praful932

**Comment by maneprajakta** [comment]
@simranbhalla3 Go ahead with this one :rocket: 
Please go through our [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) it will help you a lot in contributing to this project.

**Comment by ambivert-sam** [comment]
@Praful932  I would like to work with this issue . Can you please assign it to me?

**Comment by maneprajakta** [comment]
@simranbhalla3 Make a PR for changes done by you till now.

**Comment by simranbhalla3** [comment]
> @simranbhalla3 Make a PR for changes done by you till now.

Successfully Made the changes and Created the PR. @maneprajakta

**Comment by Sonaljain6431** [comment]
Hey @Praful932 ! I am interested to work on this issue. Would you like to assign to me?

**Comment by maneprajakta** [comment]
@Sonaljain6431 this issue is already taken. Meanwhile, you can check out other [issues](https://github.com/Praful932/Kitabe/issues) and go through [Startet Guide](https://github.com/Praful932/Kitabe/discussions/42)

**Comment by Sonaljain6431** [comment]
Ok

**Comment by maneprajakta** [comment]
@simranbhalla3 any updates?

**Comment by simranbhalla3** [comment]
> @simranbhalla3 any updates?

do i just have to create a new pull request with all the changes I had made?

**Comment by Praful932** [comment]
> > @simranbhalla3 any updates?
> 
> do i just have to create a new pull request with all the changes I had made?

Please check out our feedback on the PR you already made

**Comment by Aayu231** [comment]
Hey, I'd like to work on this issue. Any updates?

**Comment by Praful932** [comment]
@Aayu231 Go ahead 🚀

**Comment by reshchat** [comment]
@Praful932 Can I work on this issue ?

**Comment by simranbhalla3** [comment]
@Praful932 I had solved this issue but my PR isn't merged yet?
 please let me know

**Comment by maneprajakta** [comment]
@simranbhalla3 If you could go through your PR #123  you could see we didn't receive updates from your side that's why we closed your PR.

**Comment by Praful932** [comment]
@reshchat Go ahead :) Check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42)
