### ISSUE TITLE
Code Coverage for helpers.py

### ISSUE THREAD

**Issue by Praful932** [Praful932/Kitabe#33]
**Describe the bug**
The coverage of the file [helpers.py](https://github.com/Praful932/Kitabe/blob/master/mainapp/helpers.py) is low 59%.

**To Reproduce**
1. `coverage run manage.py test mainapp`
2. `coverage report`

**Expected behavior**
Code coverage for the corresponding file should be atleast `90%`

**Screenshots**
![image](https://user-images.githubusercontent.com/45713796/110078670-18df4900-7dae-11eb-8bb3-f870bc535b21.png)

**Additional context**
To increase the coverage corresponding tests have to be written in `tests.py`.
To see the code which has not been covered by tests after running `coverage report` run `coverage annotate` and open the corresponding coverage file. For more details check out the [docs](https://coverage.readthedocs.io/en/coverage-5.5/cmd.html#text-annotation-coverage-annotate).
If you are new to django testing check out [this](https://realpython.com/testing-in-django-part-1-best-practices-and-examples/).

**Definition of Done**
Code coverage for `helpers.py` is atleast 90%

**Comment by Mukta-Sawant** [comment]
@Praful932 I would like to work on this issue as a part of GSSOC'21?

**Comment by Praful932** [comment]
@Mukta-Sawant Go ahead!

**Comment by maneprajakta** [comment]
@Mukta-Sawant are you working on this issue.

**Comment by Mukta-Sawant** [comment]
@maneprajakta Yes.

**Comment by Praful932** [comment]
@Mukta-Sawant You could open a draft PR even if it's incomplete so we know it is WIP

**Comment by maneprajakta** [comment]
@Mukta-Sawant no updates from your side.

**Comment by arpit456jain** [comment]
@Praful932 sir can you please guide me what's this (code coverge.py) and from where i can learn how to it.

**Comment by Praful932** [comment]
Sure @arpit456jain, Check out [this](https://medium.com/@nathanpatnam/what-is-unit-testing-code-coverage-and-how-to-implement-and-use-them-in-python-a8f029558fe7) article on what tests & coverage is. Then check out [this ](https://realpython.com/testing-in-django-part-1-best-practices-and-examples/) article on django testing. Hope this helps.
Ping me if you have more doubts

**Comment by ayushjha952** [comment]
@Praful932 I want to contribute for this issue but I am not getting how to write unittest for methods present in helpers.py
can you help me with this?

**Comment by Praful932** [comment]
Hi @ayushjha952, for each function which isn't currently covered by tests you need to write tests which assert that the intended function returns what is expected

**Comment by ayushjha952** [comment]
@Praful932 I am not getting how to write the test case?

**Comment by ayushjha952** [comment]
Okay So can you assign this to me I can try?

**Comment by ayushjha952** [comment]
@Praful932  Do we have make any separate class or write in one of class provided in tests.py

**Comment by Praful932** [comment]
> @Praful932 Do we have make any separate class or write in one of class provided in tests.py

Separate. Although you can combine all one-liner functions/similar functions into one class.
Do you want to be assigned to this issue?

**Comment by Sukriti-sood** [comment]
@Praful932 I want to work on this.

**Comment by maneprajakta** [comment]
@Sukriti-sood Go for it, read once [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) it will help in contributing to the project.

**Comment by maneprajakta** [comment]
@Sukriti-sood you can draft a WIP PR for changes done till now.

**Comment by jonathanalvares9009** [comment]
@maneprajakta can you assign me this issue?

**Comment by maneprajakta** [comment]
@jonathanalvares9009 Go ahead also once go through [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42).

**Comment by maneprajakta** [comment]
@jonathanalvares9009 any updates?

**Comment by noobkid2411** [comment]
Hi,I would like to work on this issue,could you assign me the same!

**Comment by Praful932** [comment]
Sure go ahead @noobkid2411, do checkout the [Guide](https://github.com/Praful932/Kitabe/discussions/42) :)

**Comment by noobkid2411** [comment]
Hey,I tried generating the results before adding code to helpers.py but the execution shows an error,
Module not found:no module named allauth and further goes on to say coverage.py warning no data collected. Can I get some help in figuring out what is the issue,I have never faced this issue before so would like some insights on the same!

**Comment by maneprajakta** [comment]
@noobkid2411 did you set up the env and installed all requirements.

**Comment by Praful932** [comment]
@noobkid2411 Could you add the ss

**Comment by noobkid2411** [comment]
Hey,thanks for responding,but I was able to resolve it. Apparantly the system was failing in building wheel for the all-auth dependency. I just reinstalled django and ran it again.I'll ask if I have any more issues. Would try to add a pr for the same soon too and will keep you guys updated till then:)

**Comment by noobkid2411** [comment]
Hey,unfortunately I have a health emergency in my family to deal with.Iwould still like to contribute but I might not be able to make a pr before the 20th.If this is an urgent work,you can unassign me,sorry for the inconvenience from my side.

**Comment by subhangi2731** [comment]
@Praful932 please assign me this I want to work on this

**Comment by maneprajakta** [comment]
@subhangi2731 you can take this up!

**Comment by maneprajakta** [comment]
@subhangi2731 any updates!

**Comment by Praful932** [comment]
Not prioritized right now
