### ISSUE TITLE
Code coverage for views.py

### ISSUE THREAD

**Issue by Praful932** [Praful932/Kitabe#35]
**Describe the bug**
The coverage of the file [views.py](https://github.com/Praful932/Kitabe/blob/master/mainapp/views.py) is low 60%.

**To Reproduce**
1. `coverage run manage.py test mainapp`
2. `coverage report`

**Expected behavior**
Code coverage for the corresponding file should be atleast `90%`

**Screenshots**
![image](https://user-images.githubusercontent.com/45713796/110078670-18df4900-7dae-11eb-8bb3-f870bc535b21.png)

**Additional context**
To increase the coverage corresponding tests have to be written in `tests.py`.
To see the code which has not been covered by tests after running `coverage report` run `coverage annotate` and open the corresponding coverage file. For more details check out the [docs](https://coverage.readthedocs.io/en/coverage-5.5/cmd.html#text-annotation-coverage-annotate).
If you are new to django testing check out [this](https://realpython.com/testing-in-django-part-1-best-practices-and-examples/).

**Definition of Done**
Code coverage for `views.py` is atleast 90%

**Comment by micksharma** [comment]
Can I work on this issue ?

**Comment by maneprajakta** [comment]
Go for it @micksharma

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by Praful932** [comment]
@rk05-lenavo Checkout the starter [guide](https://github.com/Praful932/Kitabe/discussions/42)

**Comment by rk05-lenavo** [comment]
@Praful932 could you  please assign me this.

**Comment by Praful932** [comment]
@micksharma Could you open a draft PR with your present progress, so we know you're going in the right direction

**Comment by maneprajakta** [comment]
@micksharma no updates from your side.

**Comment by Nidhi-2000** [comment]
Hey @maneprajakta . Can you please assign this issue to me. I am a GSSOC'21 participant

**Comment by maneprajakta** [comment]
@Nidhi-2000 One issue at a time assigned you here #36.

**Comment by hasanmdarif** [comment]
Is anyone working on it? If not then please assign me

**Comment by Praful932** [comment]
@hasanmdarif Go ahead :)
Do checkout the [guidelines](https://github.com/Praful932/Kitabe/discussions/42)

**Comment by hasanmdarif** [comment]
> @hasanmdarif Go ahead :)
> Do checkout the [guidelines](https://github.com/Praful932/Kitabe/discussions/42)

Thanks @Praful932

**Comment by maneprajakta** [comment]
@hasanmdarif any updates?

**Comment by noviicee** [comment]
@Praful932 @maneprajakta I am willing to take this up if it is open :)

**Comment by noviicee** [comment]
I am willing to take this up if it's still open :)

**Comment by maneprajakta** [comment]
@noviicee okays go ahead.

**Comment by maneprajakta** [comment]
@noviicee were you able to figure it out?

**Comment by noviicee** [comment]
> @noviicee were you able to figure it out?

Yup! I got a solution! Trying to figure it out for once more and make a PR in a few days.
Sorry for the delay, I got my papers in between :/

**Comment by maneprajakta** [comment]
No issues :)

**Comment by maneprajakta** [comment]
@noviicee any updates?

**Comment by noviicee** [comment]
> @noviicee any updates?

Unable to increase the coverage beyond 70%  :\

**Comment by Praful932** [comment]
@noviicee We can help out, which functions are you facing issues for writing tests

**Comment by subhangi2731** [comment]
@Praful932 @maneprajakta can i work on this please

**Comment by noviicee** [comment]
> @Praful932 @maneprajakta can i work on this please

Still working on it :)

**Comment by Praful932** [comment]
Not prioritized right now
