### ISSUE TITLE
Docstrings for helpers.py

### ISSUE THREAD

**Issue by Praful932** [Praful932/Kitabe#36]
**Describe the bug**
The `helpers.py` file does not have clear docstrings for functions. Documentation of this would help developers have a clearer picture of the code.

**To Reproduce**
1. Check the [helpers.py](https://github.com/Praful932/Kitabe/blob/master/mainapp/helpers.py) file

**Expected behavior**
The docstrings of the functions should be documented according to`numpy style` guide.

**Screenshots**
Currently it only contains a docstring containing a short description of the function.
![image](https://user-images.githubusercontent.com/45713796/110203896-70f17a80-7e96-11eb-8389-3d0e642516fb.png)

**Additional context**
For numpy style docstrings refer [this](https://numpydoc.readthedocs.io/en/latest/format.html).

**Definition of Done**
All functions are documented using numpy docstring and running this `docstr-coverage mainapp/helpers.py` command results in 100% coverage.

**Comment by abhish3k-11** [comment]
@Praful932 I would like to work on this issue as a part of GSSOC'21. Can you help me on how to get started?

**Comment by vermatanu** [comment]
I want to work on this issue as a part of GSSOC'21

**Comment by Praful932** [comment]
@abhish3k-11 Since you have already commented on another issue first, I have tagged you there
Go ahead @vermatanu

**Comment by srimontidutta** [comment]
I want to get started with this for GSSoC 21. Can you please guide me on it?

**Comment by maneprajakta** [comment]
@vermatanu are you working on this issue.

**Comment by vermatanu** [comment]
@maneprajakta yes I am working on this
@Praful932 I am a beginner with GitHub, should I create a pull request after done with the work, for reviewing?

**Comment by Praful932** [comment]
@vermatanu Yes please, follow the [guide ](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md) for contribution

**Comment by YasviPatel** [comment]
hii,@praful932 I am participate at GSSoC'21 I would like to work with this issue.Would you please assign it to me?

**Comment by Praful932** [comment]
Hi @YasviPatel , Thanks for your interest in this project, This issue is already assigned. Please check the [starter guide](https://github.com/Praful932/Kitabe/discussions/42) 🙂

**Comment by maneprajakta** [comment]
Hi @ambivert-sam Thank you for showing interest :smile:. This issue is already assigned. Please check [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) which we follow.

**Comment by Praful932** [comment]
@vermatanu  Could you open a draft PR with your present progress, so we know you're going in the right direction

**Comment by vermatanu** [comment]
Hi @Praful932 I have updated the docstrings as was required for this issue and have opened a pull request. Please review and let me know the necessary changes, as needed.

**Comment by srimontidutta** [comment]
Hello, is this issue still open?

**Comment by maneprajakta** [comment]
@srimontidutta yes

**Comment by Nidhi-2000** [comment]
Hey @maneprajakta I am GSSOC'21 participant. Can you please assign this issue to me

**Comment by maneprajakta** [comment]
Go ahead @Nidhi-2000 .Go through [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) once.

**Comment by maneprajakta** [comment]
@Nidhi-2000 you can draft a WIP PR for changes done till now. So that we can review the progress.

**Comment by noviicee** [comment]
@maneprajakta is this issue still open?

**Comment by Praful932** [comment]
@noviicee Yes

**Comment by noviicee** [comment]
So can I take this up?
It just needs the function docstrings to be converted according to numpy style guide right..?

**Comment by maneprajakta** [comment]
Yes!
Go ahead @noviicee

**Comment by maneprajakta** [comment]
@noviicee check [Guide](https://github.com/Praful932/Kitabe/discussions/42) once it will help.

**Comment by noviicee** [comment]
Thanks @maneprajakta
