### ISSUE TITLE
Better Hyperparameter Search

### ISSUE THREAD

**Issue by Praful932** [Praful932/Kitabe#39]
**Is your feature request related to a problem? Please describe.**
Currently the number of components used to determine book embedding is `200`. Since it seemed to work and the search takes a lot of time for us locally, We fixed the hyperparameter to that.

**Describe the solution you'd like**
Does a better hyperaparameter exist? Can we do a Randomized Search or a Grid Search to determine that, maybe even tune other parameters? Even after finding a better one with a lesser loss, does it produce a better output when the similarity metric is used?

**Additional context**
Refer the Embedding Notebook in The Notebook & Files Section for code. You can either Integrate Surprise with ScikitLearn Grid Search or use [another ](https://github.com/Praful932/Tf-Rec) package to determine embedding and do they perform well

**Comment by micksharma** [comment]
Can I work on this issue ?

**Comment by subhangi2731** [comment]
can you assign this issue to me?

**Comment by maneprajakta** [comment]
@micksharma as you are assigned #35 
@subhangi2731 you can go ahead with this issue.

**Comment by Praful932** [comment]
@subhangi2731 Could you open a draft PR with your present progress, so we know you're going in the right direction

**Comment by subhangi2731** [comment]
sure I will @Praful932 I am working on this but I had a doubt where can I reach U?

**Comment by Praful932** [comment]
Hi @subhangi2731 you can either reach out on GSSOC Discord/start a new [discussion](https://github.com/Praful932/Kitabe/discussions/new) here

**Comment by maneprajakta** [comment]
@subhangi2731 any updates?

**Comment by subhangi2731** [comment]
Hello I was out of station I was not able to communicate and reach out to u can u please reassign me I will send the pr by today

**Comment by maneprajakta** [comment]
@subhangi2731 any updates?

**Comment by Praful932** [comment]
Hi @Sukriti-sood Yes, you can go through the [starter guide](https://github.com/Praful932/Kitabe/discussions/42), it will point you to the right resources regarding modelling and how it integrates with the project :)
If you have any specific doubt feel free to [reach out](https://github.com/Praful932/Kitabe/discussions/new)
Also just @Praful932 is fine :)

**Comment by Aditi0102** [comment]
@Praful932 I would like to work on this issue under GSSOC'21

**Comment by maneprajakta** [comment]
@Aditi0102 Go ahead :rocket: . check [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) it will help.

**Comment by maneprajakta** [comment]
@Aditi0102 any updates?

**Comment by Aditi0102** [comment]
@maneprajakta I'll complete in a day or two.

**Comment by Praful932** [comment]
@Aditi0102 You can open a WIP PR(does not need to be complete), so we can track the progress :)

**Comment by maneprajakta** [comment]
@Aditi0102 ?

**Comment by Kavs-123** [comment]
hey @Praful932  
Can I work on this issue?

**Comment by Praful932** [comment]
Sure go ahead

**Comment by Kavs-123** [comment]
> Sure go ahead

Thank you

**Comment by maneprajakta** [comment]
@Kavs-123 any updates?

**Comment by Kavs-123** [comment]
hey @maneprajakta  
I am not well, therefore,  
I won't be able to work on this issue!
I am extremely sorry for bothering you!

**Comment by maneprajakta** [comment]
@Kavs-123 No issues.
Take care :)

**Comment by Praful932** [comment]
Closing as not a priority right now
