### ISSUE TITLE
Add a favicon.

### ISSUE THREAD

**Issue by padmajabhol** [Praful932/Kitabe#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Are you willing to contribute to this issue?** [Yes/No]

**Describe alternatives you've considered**

**Additional context**

**Comment by maneprajakta** [comment]
We do have a One  :

![Screenshot from 2021-03-09 08-22-30](https://user-images.githubusercontent.com/57425995/110411739-16803600-80b1-11eb-8547-b0fc4abc80ca.png)

Do you want to improve this one, can you elaborate?
Also, do follow the Github issue template while creating a new issue.

Thanks for showing interest.

**Comment by Praful932** [comment]
@padmajabhol Please follow Issue template, I have edited your description. Make changes accordingly
Thanks for your interest

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this. Hope to hear back from you . 
Thank you .

**Comment by saumyaparikh** [comment]
I would like to contribute as a GSSOC'21 participate.

**Comment by thesakshipandey** [comment]
I've good resources to work on this issue.

**Comment by maneprajakta** [comment]
Thank You for showing interest :smiley:  @thesakshipandey but the issue is unclear.We are not assigning anyone to it until it becomes clear. Check out our [Starte Guide](https://github.com/Praful932/Kitabe/discussions/42) to know more.
