### ISSUE TITLE
Dark Mode 🌗

### ISSUE THREAD

**Issue by Praful932** [Praful932/Kitabe#41]
**Is your feature request related to a problem? Please describe.**
A switchable Dark Mode

**Describe the solution you'd like**
- Wireframe & Mockup Design
- Code Implementation

**Describe alternatives you've considered**
If there is any other alternative you would like to suggest go ahead.

**Comment by micksharma** [comment]
I want to work on this issue.

**Comment by Anurag-bhatia** [comment]
kindly assigned me this issue under the review of GSSOC'21.

I would like to add solve this issue .My code is with  clear and proper comments.

**Comment by maneprajakta** [comment]
@micksharma as you are already working on #35
as per over [Guidelines](https://github.com/Praful932/Kitabe/discussions/42) one person can take a single issue at a time.

@Anurag-bhatia You can go ahead with this one.

**Comment by Praful932** [comment]
@Anurag-bhatia Do checkout the [starter guide](https://github.com/Praful932/Kitabe/discussions/42)

**Comment by MayankBeck** [comment]
I would love to work on this issue under GSSoC 21. Can you please assign this to me?

**Comment by Anurag-bhatia** [comment]
@Praful932  do anyone mentor me or i have to work on my own. i am new to this.

**Comment by maneprajakta** [comment]
@MayankBeck Thank you for showing interest :rocket: but this issue is already assigned to someone.Do check out  our [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) for same:smile: .

**Comment by maneprajakta** [comment]
@Anurag-bhatia great :rocket:  If you have set up the project locally at your end by going through [starter guide](https://github.com/Praful932/Kitabe/discussions/42). You can start working on the issue from your end also We do have mentors for the project that can help you will let you know once we contact them :smiley: .

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by Praful932** [comment]
@rk05-lenavo Checkout the starter [guide](https://github.com/Praful932/Kitabe/discussions/42) :)

**Comment by rk05-lenavo** [comment]
Could you please assign me this.

**Comment by Praful932** [comment]
@rk05-lenavo This is already assigned, could you check out the starter guide for further info

**Comment by Praful932** [comment]
@Anurag-bhatia Could you open a draft PR with your present progress, so we know you're going in the right direction

**Comment by n-coder2k** [comment]
I want to work on this issue.

**Comment by Anurag-bhatia** [comment]
@Praful932  sir, i dont know how to get started , i am very new in this.

**Comment by maneprajakta** [comment]
@Anurag-bhatia any updates?

**Comment by mohammedjameel24** [comment]
Please assign me this issue

**Comment by Anurag-bhatia** [comment]
@Praful932 kindly unassign me from this issue, i am not able to do this.

**Comment by mohammedjameel24** [comment]
> @Praful932 kindly unassign me from this issue, i am not able to do this.

Assign me @Praful932

**Comment by maneprajakta** [comment]
@mohammedjameel24 It's a UI/UX change please go through **Very Important Points to be Noted** in our  [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42).

**Comment by Praful932** [comment]
@mohammedjameel24 Any updates?

**Comment by mohammedjameel24** [comment]
I have problem running it locally

**Comment by sandipswain** [comment]
@Praful932 I am a participant of GSSoC'21.I would love to work on this issue using JavaScript

**Comment by mohammedjameel24** [comment]
Am not able to set virtual env 
And start the deployment server

**Comment by Praful932** [comment]
@mohammedjameel24 
> Head to discussions/discord and tell us your problem :) We'll try to resolve

**Comment by maneprajakta** [comment]
@mohammedjameel24 any update?

**Comment by rk05-lenavo** [comment]
I am a GSSoC'21 participant.
Can you assign me this issue

**Comment by Praful932** [comment]
Go ahead @rk05-lenavo

**Comment by rk05-lenavo** [comment]
@Praful932 I have created the Pull request kindly check the code.

**Comment by SnehaVeerakumar** [comment]
Kindly assign me this issue. I will complete within 1 day. @maneprajakta 
You can unassign me if I don't complete in maximum of 2 days.

**Comment by SnehaVeerakumar** [comment]
Is this issue still up for grab ?
@maneprajakta

**Comment by maneprajakta** [comment]
@SnehaVeerakumar Yep. Do you want to be assigned for this one?

**Comment by CMELAKKIA** [comment]
@maneprajakta  Yes ! I can complete this issue within 1 or 2 days !!!

**Comment by SnehaVeerakumar** [comment]
@maneprajakta  YES ! I can complete this issue in 1 or 2 days !!

**Comment by maneprajakta** [comment]
Go ahead :rocket: . Read once [starter Guide](https://github.com/Praful932/Kitabe/discussions/42) it will help.

**Comment by simranbhalla3** [comment]
Hii, can i work on this?

**Comment by SnehaVeerakumar** [comment]
> Go ahead 🚀 . Read once [starter Guide](https://github.com/Praful932/Kitabe/discussions/42) it will help.

Started working on it !

**Comment by SAHU-01** [comment]
//cc @Praful932  Is this issue up to grab?

**Comment by Praful932** [comment]
@SAHU-01 Yea go ahead :)

**Comment by SAHU-01** [comment]
//cc @Praful932  would you specify if you want anything in particular about  this ,then maybe I can submit a prototype close to what you are looking for!

**Comment by maneprajakta** [comment]
@SAHU-01, not anything particular we had thought it's up to you.
It would be great if you first show us a wireframe for the same then after approval you can start working on its implementation part.

**Comment by SAHU-01** [comment]
> @SAHU-01, not anything particular we had thought it's up to you.
> It would be great if you first show us a wireframe for the same then after approval you can start working on its implementation part.



sure,I'll share my wireframe by tommorow and if you want changes,I can keep doing that  until you are satisfied with the designs,hope that sounds good to you //cc @maneprajakta

**Comment by SAHU-01** [comment]
@maneprajakta  @Praful932  would you like ui and colour pallete like this for the dark theme

![image](https://user-images.githubusercontent.com/71656941/116080828-22eb3d00-a6b7-11eb-8081-d9b0f7a8cbc5.png)

**Comment by SAHU-01** [comment]
i'll keep in mind the three divisions and the carousals you have  and restructure the design similar to the one here,would that work,or you want something a bit more classy like this one 
![image](https://user-images.githubusercontent.com/71656941/116081307-bd4b8080-a6b7-11eb-8310-515b7bd4afd1.png)

**Comment by maneprajakta** [comment]
@SAHU-01 we don't want to change the structure of the website in dark theme just a color change for dark theme would work.

**Comment by SAHU-01** [comment]
> @SAHU-01 we don't want to change the structure of the website in dark theme just a color change for dark theme would work.

ok got that,so about the colour palette i'll share that,let me know if those colours suite your taste.

**Comment by SAHU-01** [comment]
Let me know which of these colour palette you would prefer @maneprajakta @Praful932 

1.![image](https://user-images.githubusercontent.com/71656941/116092864-cc383000-a6c3-11eb-8c35-660d7aa52887.png)

2.![image](https://user-images.githubusercontent.com/71656941/116092915-d78b5b80-a6c3-11eb-8894-86a77b362854.png)

**Comment by maneprajakta** [comment]
@SAHU-01 First one works for me :+1:

**Comment by SAHU-01** [comment]
@maneprajakta @Praful932 would this wireframe suit the website,then I'd start with the code!
https://www.figma.com/file/xMOePF7WfEhOU72rKsSIwj/Untitled?node-id=0%3A1
I did not change the original layout,I simply added your chosen colour palette.

**Comment by maneprajakta** [comment]
@SAHU-01 were you able to figure out the local setup problem?

**Comment by maneprajakta** [comment]
@SAHU-01 any updates?

**Comment by maneprajakta** [comment]
No updates received. Also, we think no need for this feature till now.
