### ISSUE TITLE
Make the navbar sticky

### ISSUE THREAD

**Issue by padmajabhol** [Praful932/Kitabe#44]
**Describe the bug**
The navbar disappears as soon as we scroll down.

**To Reproduce**
1. Go to 'home page'
2. Scroll down 

**Expected behavior**
The navbar should be fixed at the top even when the user scrolls down the page.

**Screenshots**
![Screenshot (5)](https://user-images.githubusercontent.com/75530516/110447089-e2733800-80e5-11eb-9a5a-6534cd196038.png)

**Are you willing to contribute to this issue?** [Yes]

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version:

**Additional context**
All the changes made should be responsive.

**Comment by nitinjaiswal7537** [comment]
@padmajabhol  i would like contribute as a Gssoc 21  participant

**Comment by AakankshaShah** [comment]
I can work on this.

**Comment by maneprajakta** [comment]
@padmajabhol I have edited your description just go through it. So, that you can get what is supposed to be written where. 
Go ahead with this one

**Comment by shubhamgoel01** [comment]
I would like to fix this bug.

**Comment by shubhamgoel01** [comment]
@padmajabhol hey i solve this issue .

**Comment by Praful932** [comment]
@shubhamgoel01 Check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42) 🙂

**Comment by MayankBeck** [comment]
I would love to work on this issue under GSSoC 21. Can you please assign this to me?

**Comment by shubhamgoel01** [comment]
> @shubhamgoel01 Check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42) 🙂

@Praful932  I did that , i mean to say please check my merge request, i make navbar sticky

**Comment by maneprajakta** [comment]
@MayankBeck Thank you for showing interest :rocket:  but this issue is already assigned to someone. Please go through our [Starte Guide](https://github.com/Praful932/Kitabe/discussions/42) once :smiley: .

**Comment by Praful932** [comment]
I think we should class this @maneprajakta Since the icon has been added, this wouldn't look good @maneprajakta

**Comment by maneprajakta** [comment]
Yep @Praful932 also we are adding a button to go top that will do great.
