### ISSUE TITLE
A like button for each book and affiliate links to buy books from various e commerce sites

### ISSUE THREAD

**Issue by AakankshaShah** [Praful932/Kitabe#46]
### Is your feature request related to a problem? Please describe.
No, it's an additional feature.

### Describe the solution you'd like
I would like to propose a solution where readers can like the book of their taste and also avail the buying feature that will redirect them to the e-commerce sites.

###  Are you willing to contribute to this issue? 
Yes, I am willing to contribute.

**Comment by AakankshaShah** [comment]
I am a GSSOC'21 participant and would like to work on it.

**Comment by maneprajakta** [comment]
@AakankshaShah  Can you please follow the Issue template.
I have updated the issue description. Please make changes accordingly.

**Comment by Praful932** [comment]
@AakankshaShah We had a similar issue created #45. As for the like button, we already have a rate option, that would suffice. 
Check out the [contributor guide](https://github.com/Praful932/Kitabe/discussions/42) for further details

Thanks
