### ISSUE TITLE
Making the site responsive.

### ISSUE THREAD

**Issue by kanchi-22** [Praful932/Kitabe#47]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Are you willing to contribute to this issue?** [Yes/No]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maneprajakta** [comment]
@kanchi-22  Can you please follow the Issue template.
I have updated the issue description. Please make changes accordingly.
