### ISSUE TITLE
Color pallete & font enhancement

### ISSUE THREAD

**Issue by ketakitankk** [Praful932/Kitabe#48]
**Describe the bug**
The navigation bar of the site should be full of the name of the venture, however, the ne of the venture itself is extremely small in size and has not been aligned properly, the color palette of the site can be more vibrant and attractive and the fonts can be changed too. I feel in doing so, the site will attract traffic and be a successful one at it.

**To Reproduce**
1. Go to "https://kitabe-app.herokuapp.com/"
2. Scroll down to the very end 
3. Made me realize the site can have a vibrant color palette and the font sizes can also be adjusted to the desired sizes.

**Expected behavior**
Learning that this is a site about books, I feel the content can be edited to a more readable text and a formal one at that too.
**Screenshots**

**Are you willing to contribute to this issue?**
 YES

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**
All changes made should be responsive.

**Comment by maneprajakta** [comment]
@ketakitankk I have updated the *Additional Context*  for the issue description just check once.
Also, are you contributing under GSSOC'2021

**Comment by ketakitankk** [comment]
@maneprajakta yes, I’m a participant at GSSOC ‘21

**Comment by maneprajakta** [comment]
Go ahead with this one @ketakitankk

**Comment by shubhamgoel01** [comment]
You can make your navbar-footer section in base class, and inherit that into other html files(Explore.html) and put body or any section into base class using  . basically its template inheritance. Easy to manage and build site in more attractive way

**Comment by Praful932** [comment]
@ketakitankk Check out the Important Notes in the [starter guide](https://github.com/Praful932/Kitabe/discussions/42). There are specific points for UI/UX improvements/fixes

**Comment by maneprajakta** [comment]
@MayankBeck @salonidabgar Thanks for showing interest :star2: But this issue is already assigned to someone . Once go through our [Starte Guide](https://github.com/Praful932/Kitabe/discussions/42) it would be more clear :smile: .

**Comment by ketakitankk** [comment]
Hi @maneprajakta , I have created a mockup design of the landing page, please check it out and let me know asap! 
https://app.moqups.com/WDod2wWXrw/view/page/a5a593ec7

**Comment by ketakitankk** [comment]
Hi @Praful932 , I have created a mockup design of the landing page, please find the attachment and let me know asap!
https://app.moqups.com/WDod2wWXrw/view/page/a5a593ec7

**Comment by maneprajakta** [comment]
@ketakitankk If you could give access to view the mockup design.

**Comment by ketakitankk** [comment]
> @ketakitankk If you could give access to view the mockup design.

I have made the changes. You can view the mock-up design now.

**Comment by maneprajakta** [comment]
@ketakitankk  color palette looks great to me :rocket: .
Carousel of quotes, till that everything seems fine. I think we don't need the section **Brief introduction of the webpage, what it does, why it has been made,  how it works etc.**
In **Carousel Of Book Section**   you want to move the current **popular among users section** there but we don't have a chapter inside books if you could check once what information about every book we have then it would be easy for you to design accordingly.
In *Search your pick by genre* that is current **Read genre-wise** if I select a genre from drop-down where the books will be shown?
Also *Select if you want a recommendation from famous authors* how that button will work?
**Testimonial Section** it looks great to me but we are not taking any feedback from users on how accurate where the books recommended to them. So a feedback functionality needs to be added to the project then only the testimonial section will get some content.
**Meet the creator** I don't think we need this section what you think @Praful932 on this.

**Comment by ketakitankk** [comment]
I shall submit another mockup soon @maneprajakta , countering all the issues you have mentioned in my current mockup.
Thank you.

**Comment by Praful932** [comment]
Hi @ketakitankk Great job on the quick mockups, I believe this issue is too broad and it is possible that this may go out of scope according to what I'm seeing from your mockup. The mockup should match exactly what currently is available on the application(backend code would have to be written according to it, if any additional feature is added). 
Agree with @maneprajakta , that is not needed.
Looking forward to your second mockup

**Comment by maneprajakta** [comment]
@ketakitankk any updates?

**Comment by ketakitankk** [comment]
Yes please give me time till noon I shall present the second mockup! 
Sorry for the delay!

**Comment by ketakitankk** [comment]
Here is the second mockup, I have maintained the webpage element's placing, I have just added some font changing ideas, some color and change in some icons. Please have a look and let me know!
Thank you for your  co-operation! @maneprajakta 

![mockup 2](https://user-images.githubusercontent.com/65545601/111282491-114c5980-8664-11eb-84e3-dfd46142d62f.png)

**Comment by maneprajakta** [comment]
@ketakitankk 
All ideas suggested in the mockup are great :rocket: .
But it would be a big issue if you start working on it as a whole.
I would suggest you, go first for color scheme updation and then for other changes.
what you say @Praful932

**Comment by ketakitankk** [comment]
@maneprajakta please let me know, as to when I can start working on the issue! Thanks a lot 😊

**Comment by Praful932** [comment]
@ketakitankk UI looks nice, but I believe this would be a really big change.
We would need a detailed mockup of off the latest [application](https://kitabe-app.herokuapp.com/),
From what I observe from the present mockup, you're mostly changing the color scheme and the font scheme and minimal strucuture, If you could provide a more detailed mockup for the application, with all the correct colors,fonts of how exactly you want it to look, we can provide a more detailed feeback.

**Comment by ketakitankk** [comment]
> @ketakitankk UI looks nice, but I believe this would be a really big change.
> 
> We would need a detailed mockup of off the latest [application](https://kitabe-app.herokuapp.com/),
> 
> From what I observe from the present mockup, you're mostly changing the color scheme and the font scheme and minimal strucuture, If you could provide a more detailed mockup for the application, with all the correct colors,fonts of how exactly you want it to look, we can provide a more detailed feeback. 

Sure, could you maybe suggest me a good mock-up creating tool, in order to incorporate all my changes in one prototype? This is my first time making mock-ups! 😃

**Comment by maneprajakta** [comment]
@ketakitankk [check this](https://www.figma.com/) for mock up.

**Comment by maneprajakta** [comment]
@ketakitankk any updates?

**Comment by ketakitankk** [comment]
@maneprajakta sorry, but if you can give me time till Thursday, I can present it then, or if the issue is to be given to others, you may. Due to unavoidable circumstances, I won't be able to present before Wednesday. Sorry for the inconvenience.

**Comment by simranbhalla3** [comment]
Can i work on this issue? @Praful932

**Comment by Praful932** [comment]
@simranbhalla3 You already have one pending PR #123 , Please check :)

**Comment by harshita2319** [comment]
Hey, I'm a participant of Gssoc and I'd like to work on this issue. Please let me know if I can!

**Comment by maneprajakta** [comment]
@harshita2319 Yes, assigning you.
Go through Very Important Points to be Noted section under [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42)

**Comment by harshita2319** [comment]
Though some of the points are similar to those given by the previous assignee but I too feel that these changes are required.
I've demonstrated the color scheme as well, though I've got a few more color palettes in mind for this, so let me know in case you didn't like this, I'll switch to another one.

[https://www.figma.com/file/x2PcvAscy7cWQsBHGOPD90/second-copy-color]

**Comment by harshita2319** [comment]
Though some of the points are similar to those given by the previous assignee but I too feel that these changes are required.
I've demonstrated the color scheme as well, though I've got a few more color palettes in mind for this, so let me know in case you didn't like this, I'll switch to another one.

[mockup](https://www.figma.com/file/x2PcvAscy7cWQsBHGOPD90/second-copy-color)

**Comment by maneprajakta** [comment]
@harshita2319 can you make a mockup only for color scheme that you wish first.
- After this, we can go for other changes suggested or another issue can be created for that.

**Comment by harshita2319** [comment]
> @harshita2319 can you make a mockup only for color scheme that you wish first.
> - After this, we can go for other changes suggested or another issue can be created for that.

Yeah okay, I'll prepare another one, will share the link in a day or two.

**Comment by maneprajakta** [comment]
@harshita2319 any updates?

**Comment by harshita2319** [comment]
> @harshita2319 any updates?

On it. Sorry for the delay!

**Comment by harshita2319** [comment]
I've made a mockup, used different color schemes for you to choose. 
[one](https://www.figma.com/file/XmKLvuQb5JDMrOc3Pgq1nD/color1?node-id=0%3A1)
[two](https://www.figma.com/file/2hiiYwJwMYjDrqpl0nuiDk/color-2?node-id=0%3A1)
[three](https://www.figma.com/file/eFIDZtvH8luyEGILXzD61Q/color-3?node-id=0%3A1)
[four](https://www.figma.com/file/vaT2So0GfK03sjFZ7K6WIo/color-4?node-id=0%3A1)

**Comment by Praful932** [comment]
Hi @harshita2319 appreciate you going all out on this, We had a look at the links you posted. What we want from this issue is a different color scheme/font enhacement, not a whole layout change. A very specific wireframe of how you expect the website to look would be appreciated.
Thanks

**Comment by harshita2319** [comment]
> Hi @harshita2319 appreciate you going all out on this, We had a look at the links you posted. What we want from this issue is a different color scheme/font enhacement, not a whole layout change. A very specific wireframe of how you expect the website to look would be appreciated.
> Thanks

Hey, I can't seem to understand what you mean by a specific mockup. Could you please elaborate a bit

Or maybe just add a link to a mockup like that for any website, for my reference. I'd really appreciate!

**Comment by maneprajakta** [comment]
@harshita2319 Ya currently the mockup you have shown you are suggesting changes in different section for example banner carousel what we expect in a mockup is that website structure and content to remain the same . Make an exact copy of the home page on Figma and change color there for example bg color of website and add color pallete at the top showing all color being used. 
Check [this](https://visme.co/blog/website-color-schemes/#:~:text=22%20Corporate%20and%20Traditional&text=If%20you're%20looking%20for,of%20the%20colors%20used%20here.) to get idea .
Still not clear then let us know.

**Comment by Praful932** [comment]
You could also check this for [reference](https://www.figma.com/file/quY3GKiD5RgWhsJAg2PKyE/Kitabe?node-id=0%3A1)

**Comment by harshita2319** [comment]
Took another stab at it, please have a look.
Thanks for helping!
[first](https://www.figma.com/file/XmKLvuQb5JDMrOc3Pgq1nD/mockup2?node-id=0%3A1), [second](https://www.figma.com/file/0pB1d9l4fKfyFXmGuxQDUM/mockup1?node-id=0%3A1)

**Comment by Praful932** [comment]
> Took another stab at it, please have a look.
> Thanks for helping!
> [first](https://www.figma.com/file/XmKLvuQb5JDMrOc3Pgq1nD/mockup2?node-id=0%3A1), [second](https://www.figma.com/file/0pB1d9l4fKfyFXmGuxQDUM/mockup1?node-id=0%3A1)

Thanks for the mockups. 
I checked both of these, I'm not sure if they go in accordance with the theme of the project. Could you try some themes which if you put side by side with the current state of the project, you would choose the new one than the current one

**Comment by harshita2319** [comment]
> > Took another stab at it, please have a look.
> > Thanks for helping!
> > [first](https://www.figma.com/file/XmKLvuQb5JDMrOc3Pgq1nD/mockup2?node-id=0%3A1), [second](https://www.figma.com/file/0pB1d9l4fKfyFXmGuxQDUM/mockup1?node-id=0%3A1)
> 
> Thanks for the mockups. 
> I checked both of these, I'm not sure if they go in accordance with the theme of the project. Could you try some themes which if you put side by side with the current state of the project, you would choose the new one than the current one


And by trying out new themes you mean playing with the font of the card text and the color scheme without affecting the basic layout of the website i.e the position of the images, individual boxes and all that..right?

Sorry, if I'm asking too many questions, just want to be sure!

**Comment by maneprajakta** [comment]
Yes!
No issues :)

**Comment by harshita2319** [comment]
Hey, have a look and suggest the changes required.
I've just added one extra element..that yellow box, can remove that if needed and introduce that color somewhere else as it goes well and will help to accentuate.

[Mockup](https://www.figma.com/file/4TLJEYoQa2yms4JniLwThz/mockup1?node-id=0%3A1)

**Comment by maneprajakta** [comment]
@harshita2319 
Hi 
Went through the mock-up the colors seem dark to me. By keeping the theme of the website in mind could you pick some colors in light shades.

**Comment by harshita2319** [comment]
> @harshita2319
> Hi
> Went through the mock-up the colors seem dark to me. By keeping the theme of the website in mind could you pick some colors in light shades.

[Mockup](https://www.figma.com/file/4TLJEYoQa2yms4JniLwThz/mockup1?node-id=0%3A1)
Attached the link.

**Comment by Praful932** [comment]
Hi @harshita2319 Could you ping us on discord?

**Comment by maneprajakta** [comment]
@harshita2319 any updates?

**Comment by harshita2319** [comment]
> @harshita2319 any updates?

Hey ya on it! I was unwell, kinda better now so I've started working. Sorry for the delay!

**Comment by Praful932** [comment]
Closing this, since color pallete enhancement is not needed anymore
