### ISSUE TITLE
Adding more sorting features and filters

### ISSUE THREAD

**Issue by AakankshaShah** [Praful932/Kitabe#49]
### Is your feature request related to a problem? Please describe.
No,its an additional feature.
### Describe the solution you'd like
I would like to add more filters for sorting the books on the basis of languages, authors, likes, series or not and many more on the similar lines.

### Are you willing to contribute to this issue?
**Yes**

**Comment by maneprajakta** [comment]
@AakankshaShah  Can you please follow the Issue template.
I have updated the issue description. Please make changes accordingly.

**Comment by Praful932** [comment]
Hi @AakankshaShah Thanks for your interest in the project. Could you elaborate a bit further? How would you like this feature to be? Do you want to have a separate page? Do you want to able to search in what way, how would you implement the sort?
The scope is pretty broad here

**Comment by AakankshaShah** [comment]
In the genre (existing) page I would like to add the sorting page  to filter and sort  books according to authors, ratings,languages etc.

![image](https://user-images.githubusercontent.com/55951533/110627634-39513e00-81c8-11eb-8edb-1b5e1b2e1d44.png)

**Comment by maneprajakta** [comment]
@AakankshaShah Genre page shows top 16 books belonging to that genre which are having maximum weighted rating which is based on the rating given by the user. 
This [Section](https://github.com/Praful932/Kitabe/blob/91c168d1bcd5888c835fc48bf3ff3e0ac05064b7/mainapp/helpers.py#L98) will make it more clear how this works.
Also, go through our [Starter Guide ](https://github.com/Praful932/Kitabe/discussions/42) it will help you in getting started with the project :smile: .
Can you elaborate on how in a particular genre you want to put filter option if you go by the language? Also how by author's name?

**Comment by maneprajakta** [comment]
@AakankshaShah any updates?

**Comment by maneprajakta** [comment]
No updates received.
