### ISSUE TITLE
Feat: Better UI for signup page

### ISSUE THREAD

**Issue by WaderManasi** [Praful932/Kitabe#50]
**Is your feature request related to a problem? Please describe.**
Better UI for signup page.

**Describe the solution you'd like**
Signup page UI ,Signup Form can be updated with latest styling design using responsive frontend framework - "Materialize"
![signup](https://user-images.githubusercontent.com/52437677/110506114-d195e700-8124-11eb-9e34-60fecb0dabe0.PNG)

**Are you willing to contribute to this issue?** [Yes/No]
Yes, I would like to contribute on this issue being part of gssoc'21

**Additional Context**
Everything should be responsive.

**Comment by nNikita1018** [comment]
Yes I would like to contribute on this issue .
Please assign me

**Comment by maneprajakta** [comment]
@nNikita1018 Thanks for showing interest :smiley:  Please read our [Guidelines](https://github.com/Praful932/Kitabe/discussions/42) once.

**Comment by Praful932** [comment]
Hi @WaderManasi Thanks for showing interest in our project 😇
Are you going to change the UI or make it responsive? If there is a UI change, then to keep it consistent we would need changes on the Login page as well, keeping into account the theme of the project

**Comment by Praful932** [comment]
Great @WaderManasi Go ahead, Be sure to follow the Important Notes in the [Guidelines](https://github.com/Praful932/Kitabe/discussions/42)

**Comment by Ankita297** [comment]
Can i work on this ?

**Comment by Praful932** [comment]
Go ahead @Ankita297

**Comment by maneprajakta** [comment]
@Ankita297 you can draft a PR for whatever changes you have done till now. so that we review it.

**Comment by Ankita297** [comment]
Okay mam . I will make the PR .

**Comment by maneprajakta** [comment]
@Ankita297 go through our [Satret Guide](https://github.com/Praful932/Kitabe/discussions/42) it's a UI/UX change first you need to present a mockup.

**Comment by Ankita297** [comment]
![Sign Up - Google Chrome 17-03-2021 10_14_18](https://user-images.githubusercontent.com/67833077/111416283-9d648c80-8709-11eb-8174-e47ad6d66571.png)

**Comment by Ankita297** [comment]
Mam i am also going to   do some changes in form also ,in button styling .

**Comment by maneprajakta** [comment]
@Ankita297 no need to call ma'am :)
Also, you need to do some changes in the login form as they should match.
So, do all changes then make a PR. We just wanted to take an update.

**Comment by Ankita297** [comment]
okay @maneprajakta  i will  do the same.
Is  above changes are okay .

**Comment by maneprajakta** [comment]
Seems great to me :rocket: till now.

**Comment by ambivert-sam** [comment]
@WaderManasi can work on this issue? Please assign it to me

**Comment by maneprajakta** [comment]
@ambivert-sam check out [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42)
