### ISSUE TITLE
Suggesting books by the writer

### ISSUE THREAD

**Issue by Mirnalin** [Praful932/Kitabe#57]
If one seems to be interested in a book by a particular writer, we suggest them more books by the same writer.

I'm an GSSoC'21 participant please assign this issue to me.

**Comment by Mirnalin** [comment]
Example : If an individual is interested in say Fault in our stars by John Green, so the feature will suggest more books by John Green like Looking for Alaska, Paper towns and many more.

**Comment by maneprajakta** [comment]
@Mirnalin please follow the issue template for creating an issue.
