### ISSUE TITLE
Improvement in the footer

### ISSUE THREAD

**Issue by neha-baisane** [Praful932/Kitabe#59]
The footer does not contains Contact information, mode of payment and other things hence it looks very dull. As a GSSOC'21 participant i would like to work on the issue.
![new](https://user-images.githubusercontent.com/64725427/110678017-d5e10380-81fb-11eb-9135-59737a4298fa.PNG)

**Comment by Praful932** [comment]
Hi @neha-baisane Thank you for your interest in this project 🙂
We had 2 similar issues #45 Check [this](https://github.com/Praful932/Kitabe/issues/45#issuecomment-794979602) thread out. 
Check out the [guidelines](https://github.com/Praful932/Kitabe/discussions/42) for other ways to contribute to this project!
