### ISSUE TITLE
Google Authentication

### ISSUE THREAD

**Issue by sneha-nitdgp** [Praful932/Kitabe#60]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Are you willing to contribute to this issue?** [Yes/No]

**Describe alternatives you've considered**

**Additional context**

Google authentication would allow the users to sign up by just a single click, instead of manually signing up and logging in. I'd love to add this feature.

**Comment by sneha-nitdgp** [comment]
Can you please assign this to me?

**Comment by Praful932** [comment]
@sneha-nitdgp Please follow the Issue template :) After filling it I can mark it as a valid issue
Google Sign in is there except it's on the signup page
![image](https://user-images.githubusercontent.com/45713796/110832414-49007d80-82c1-11eb-9bb6-9fa00952b39d.png)
We can change it to **Sign In** on the Sign in Page, and a similar button on the Sign Up page as *Sign up with Google*
What do you think @maneprajakta 
I believe this would be a valid issue, If you update it, we can assign it to you :)

**Comment by sneha-nitdgp** [comment]
@maneprajakta @Praful932 Yes, I'll  change the Sign up with Google button to Sign in with google on the login page, and in sign-up page add this as Sign up with Google.
Can I work on it?

**Comment by maneprajakta** [comment]
@sneha-nitdgp Yes go ahead with this one :rocket:

**Comment by maneprajakta** [comment]
@sneha-nitdgp 
- Maintain the theme of the project.
- Also take care of Responsiveness.

**Comment by sneha-nitdgp** [comment]
Sure! Thanks for assigning.

**Comment by sneha-nitdgp** [comment]
@maneprajakta   @Praful932   Hey, I'm getting this error while setting up the project locally and trying to migrate.
raise KeyError(key) from None
KeyError: 'HOME'
Can you please help me out?

**Comment by Praful932** [comment]
@sneha-nitdgp Update your fork, see the guide :)

**Comment by maneprajakta** [comment]
@sneha-nitdgp refer **FAQ section** in [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42).

**Comment by maneprajakta** [comment]
@sneha-nitdgp Make PR for changes done till now.So that we know whether you are going right.
