### ISSUE TITLE
Top button for the home and explore page.

### ISSUE THREAD

**Issue by kanishka8276** [Praful932/Kitabe#63]
**Is your feature request related to a problem? Please describe.**
The options to sign up, logout, explore or other such options are available on the top of the home page and explore page, but when you are scrolling down and you want to use one of these options you have to scroll all the way to the top of the page Which is tidious.

**Describe the solution you'd like**
A very good solution to this problem will be a top button on the bottom right corners of the home and explore page. This button can have an upward arrow or top written on it and it will take you to the top of the page when clicked. The button can be customised and made attractive using CSS.

**Are you willing to contribute to this issue?** 
Yes, I am a participant in GsSOC'21.

**Describe alternatives you've considered**
I thought of using a sticky navigation bar but personally I don't like that kind of navigation bar, it covers the contents and is irritating.

**Comment by maneprajakta** [comment]
@kanishka8276 The issue seems right but please follow the issue template for creating a feature request issue 🙂.
I have edited your issue description please make changes to it accordingly. You can check [this](https://github.com/Praful932/Kitabe/issues/58) to get clarity about what we aspect in an issue description.
Also, go through our [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) it will help you in getting started with contributing to the project :rocket: .

**Comment by kanishka8276** [comment]
I have edited the comment. Elaborating this issue. I will like to solve this issue. Please assign this to me.

**Comment by maneprajakta** [comment]
@kanishka8276 It looks great now :rocket: .We do have an issue that will add a sticky navbar but having a button to go to the top is a nice feature.
As it is a UI/UX issue please go through the **Very Important Points to be Noted** section in [Starte Guide](https://github.com/Praful932/Kitabe/discussions/42) also maintain the theme of the project.
Go ahead with this one :smile:

**Comment by kanishka8276** [comment]
Ok, thank you ☺️

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by Praful932** [comment]
@rk05-lenavo Please read the [guidelines ](https://github.com/Praful932/Kitabe/discussions/42)🙂
Thanks
