### ISSUE TITLE
New Feature: Library

### ISSUE THREAD

**Issue by Fairspy** [Praful932/Kitabe#64]
**Is your feature request related to a problem? Please describe.**
A new page having a list of already read books by the user.

**Describe the solution you'd like**
I would like to create a new page which has a list of all the already rated books by the user which can be accessed through the navbar, the theme of the page would be consistent with the website.

**Are you willing to contribute to this issue?** Yes, I am willing to contribute to this issue as a participant in Gssoc'21.

**Describe alternatives you've considered**
None as of yet.

**Additional context**
As an avid reader myself I feel that having a page with books that have been already read by the user is an important feature.

**Comment by maneprajakta** [comment]
@Fairspy the feature seems great to me :rocket: .But have you thought about how you will be implementing this
This section will be visible in the navbar only when the user signs in. After that, you need to fetch the books rated by the user from the database and render them on-page.
Also, go through our [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) it will help you a lot to get started with this project :smile: .

**Comment by Fairspy** [comment]
@maneprajakta I actually went through the code and that's when I got the idea for this feature the section will only be visible after user authentication Which is quite easy to implement. As for fetching books rated by the user there are two functions that I thought would help me with the same in `helpers.py` I could make use of `get_rated_bookids` function to get the list of book ids of already rated books and I could use this list as input to the function `get_book_dict` to get the book details which would be used as the context for the rendered template.
As for, when there are no books rated I actually hadn't thought of that but I am thinking that we could put an if else statement and simply redirect the user to the index view if they haven't rated any books with an error message of Please rate or add books it should work.
Please let me know if I have misinterpreted something or there is a better way to do this.

**Comment by maneprajakta** [comment]
@Fairspy I hope you are clear that we will need a function in views.py to handle it and url.py will be referenced to it accordingly.
Now coming to the function which will handle everything in views.py it will filter out all the ratings given by the user to different books [Sort of Like this](https://github.com/Praful932/Kitabe/blob/91c168d1bcd5888c835fc48bf3ff3e0ac05064b7/mainapp/views.py#L57) from here onwards your approach it's correct :rocket: first `get_rated_bookids` then `get_book_dict` and at last rendering.
If user has not rated anything than what I could think is put if condition if length of list is 0 then render on page simple message that rate some book and in else the remaining part :star2: .
All set then.

**Comment by Fairspy** [comment]
@maneprajakta I do have an understanding on how to write the necessary function in views.py to handle the request as well as to update urls.py accordingly.
As for the condition when there are no books rated your idea seems doable.
So, should I start working on it?

**Comment by maneprajakta** [comment]
@Fairspy  Yes go for it :rocket: .

**Comment by Fairspy** [comment]
Great!
Thanks a lot.

**Comment by Praful932** [comment]
@Fairspy Nice job for thoroughly thinking about it! 🚀
- In case of 0 books you can reuse the message which shows when users with 0 rated books trys to enter recommendation section.
- Make sure to write the corresponding unit tests :)
- You also need to add a wireframe/mockup for the page that you are designing before the implementation

**Comment by maneprajakta** [comment]
@Fairspy also everything needs to be responsive.

**Comment by Fairspy** [comment]
@Praful932 @maneprajakta I'll definitely keep all of these points in mind while implementing the page.
As for the wireframe I'll try to make one as soon as possible. I was thinking that I could make it similar to the genres page of the website but without the rate this book button as it's already been rated.

**Comment by maneprajakta** [comment]
@Fairspy Great
 Yep, np. I think it would be nice if you go for horizontal cards for an individual book.

**Comment by Fairspy** [comment]
@maneprajakta 
Do you want something like this?
Large screen size:
![Desktop.png](https://user-images.githubusercontent.com/64915836/110961022-5d05b700-8375-11eb-8728-82789dd7020a.png)


Small screen size:
![Mobile.png](https://user-images.githubusercontent.com/64915836/110961127-7870c200-8375-11eb-80e5-9e3a1035318c.png)

I was also thinking of adding pagination for users with more than 20 read books let me know what you think about it.

**Comment by maneprajakta** [comment]
Yes, seems cool.
Ya, it's nice after 10 books you can go for pagination.

**Comment by Praful932** [comment]
@Fairspy On large screen it would be nice if you could center the card info

**Comment by Fairspy** [comment]
@maneprajakta Great then I'll start working on pagination.
@Praful932 Did you want it to be something like this?
![Screen Shot 2021-03-13 at 17.25.19.png](https://user-images.githubusercontent.com/64915836/111029904-4ae35180-8425-11eb-8720-de077006ead2.png)

**Comment by Praful932** [comment]
@Fairspy yes
@maneprajakta Adding the rating button too here would be better right, incase the user wants to change the rating?

**Comment by maneprajakta** [comment]
@Praful932 Yes agree with you adding a rating button here will also be great.
@Fairspy also look for font size like make this card look better because it looks like a lot of white space is there.

**Comment by Fairspy** [comment]
@maneprajakta @Praful932  Please take a look and let me know if any further changes are required.
Small screen sizes:
![Screen Shot 2021-03-13 at 20.48.06.png](https://user-images.githubusercontent.com/64915836/111035284-ba663a80-843f-11eb-8cdb-3bf45db9c673.png)
Large screen sizes:
![Screen Shot 2021-03-13 at 20.49.29.png](https://user-images.githubusercontent.com/64915836/111035321-ed103300-843f-11eb-9d20-4495ec6633d7.png)
I've also added the pagination let me know what you think.

**Comment by Praful932** [comment]
LGTM @Fairspy

**Comment by maneprajakta** [comment]
Go ahead @Fairspy

**Comment by Fairspy** [comment]
Great, I'll start working on it.
