### ISSUE TITLE
Design Enhancement in login Form

### ISSUE THREAD

**Issue by sujoy-coder** [Praful932/Kitabe#65]
**Is your feature request related to a problem?**
The existing Login Form has minimal design which may lead to a bad impact for users.

**Describe the solution you'd like**
I would like to redesign the login page with material bootstrap as a frontend work.

**Are you willing to contribute to this issue?** [Yes/No]
Yes, I am ready to contribute in the same issue. I am a participant in GsSOC'21
Please assign it to me.

Thank You 🙏

**Existing Login Page**

![dmo](https://user-images.githubusercontent.com/65298629/110808616-2adb5300-82aa-11eb-976f-96d73587b38c.PNG)

**Comment by maneprajakta** [comment]
@sujoy-coder we already have  #50 issue for the same.
Thanks for showing interest :rocket: .

**Comment by sujoy-coder** [comment]
Oops Sorry My bad, I thought #50 was for only signup page only. 🙇‍♀️
