### ISSUE TITLE
Add techstack used in readme 

### ISSUE THREAD

**Issue by rohank2502** [Praful932/Kitabe#70]
**Is your feature request related to a problem? Please describe.**
Yes it is a feature request from improvement of read me file !!

**Describe the solution you'd like**
I will like to add tech stacks used in this project with their logos this will make our project look much more attractive will like to work on this issue as soon as I get assigned !!

**Are you willing to contribute to this issue?** [Yes/No]
yes ( GSSOC21)

**Describe alternatives you've considered**
I will like to update the read me 

Will look like this ( Example of my work )
![Screenshot 2021-03-12 224657](https://user-images.githubusercontent.com/76584243/111018461-e1d8eb00-83de-11eb-9f6f-ca63f9417470.png)

**Comment by maneprajakta** [comment]
@rohank2502 I have edited your issue description please complete it accordingly. 
 You can check this #58 issue to see what we aspect in an Issue description. so, that you can move forward.

**Comment by rohank2502** [comment]
Ok sorry !! I will do it !

**Comment by Praful932** [comment]
I don't think this is needed, It's easily conveyed from the github tags...
