### ISSUE TITLE
Environment Set Up not working in Windows

### ISSUE THREAD

**Issue by WaderManasi** [Praful932/Kitabe#73]
**Describe the bug**
The command given for activating the environment (in CONTRIBUTING.MD file) is not working on windows platform. Instead the given commands work on Linux/Unix machines. I got error while running this command as "source is not recognized as internal or external command".

**To Reproduce**
I would like add command which executes on windows system.

**Screenshots**
![a1](https://user-images.githubusercontent.com/52437677/111019234-e18f1e80-83e3-11eb-8b1b-2beadfde3fb4.PNG)

**Are you willing to contribute to this issue?** [Yes/No]
Yes
**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Praful932** [comment]
@WaderManasi Go ahead
Something of the like
- Linux/Unix - `source bookenv/Scripts/activate`. Windows - ...

**Comment by WaderManasi** [comment]
Sure.
