### ISSUE TITLE
Better UI for book list in the explore page

### ISSUE THREAD

**Issue by AmrutaKoshe** [Praful932/Kitabe#74]
**Describe the bug**
When you hover over any book displayed in the explore page, 2 buttons (More Details, Rate this book) appear below the book div. This causes all the divs under this block to be shifted downwards, which appears to be messy and confusing.

**To Reproduce**
1. Go to https://kitabe-app.herokuapp.com/
2. Click on the explore button in the top right corner
3. Hover over any book and see how it changes when you unhover. 

**Expected behavior**
We can keep the layout consistent and change the divs in the explore page so that they are similar to the book list appearing in any genre page. For example: https://kitabe-app.herokuapp.com/genre_books/Fantasy 

**Screenshots**
![image](https://user-images.githubusercontent.com/59871941/111020244-709f3500-83ea-11eb-98ff-c246b7f1781e.png)

The buttons that have appeared under the first book make the page look messy.

It could be made similar to the books in genre list
![image](https://user-images.githubusercontent.com/59871941/111020254-83196e80-83ea-11eb-8d47-7101678b3d32.png)

**Are you willing to contribute to this issue?** 
Yes. I would like to contribute to this issue as a Gssoc'21 participant.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 89

**Smartphone (please complete the following information):**
 - Device: Redmi K20

**Additional context**

**Comment by Praful932** [comment]
@AmrutaKoshe Good catch! 
@maneprajakta Check this out

**Comment by maneprajakta** [comment]
@AmrutaKoshe @Praful932 
Yep seems cool to me.

**Comment by maneprajakta** [comment]
@AmrutaKoshe Go ahead with this one
But before that for through **Very Important Points to be Noted** section in [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) :rocket: .

**Comment by AmrutaKoshe** [comment]
> @AmrutaKoshe Go ahead with this one
> But before that for through **Very Important Points to be Noted** section in [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) 🚀 .

Ok sure! Thanks
