### ISSUE TITLE
Updation in contributing.md

### ISSUE THREAD

**Issue by kanishka8276** [Praful932/Kitabe#77]
**Describe the bug**
Allowed_hosts=['127.0.0.1'] doesn't work in some browsers. It shows an error to add 'localhost' in Allowed_hosts.

**Expected behavior**
I expected to see the pages  but it showed errors.

**Are you willing to contribute to this issue?** [Yes/No]
Yes, I am a participant in GsSOC'21.
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser :Chrome
 

**Additional context**
We just need to add "localhost" to the Allowed_hosts and then it works fine.
![Screenshot (62)](https://user-images.githubusercontent.com/66053534/111031030-8e40be80-842b-11eb-9725-921b57751815.png)

**Comment by Praful932** [comment]
Hi @kanishka8276 Could you update the issue with a ss of the issue that you're facing?

**Comment by kanishka8276** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/66053534/111030985-4883f600-842b-11eb-835f-5969b7d7183a.png)
This is the error which I got. Then I added 'localhost' to Allowed_Hosts and it worked.

**Comment by Praful932** [comment]
@kanishka8276 go ahead!
