### ISSUE TITLE
Adding a home button to go to index.html instead of using "Kitabe" to go to home.

### ISSUE THREAD

**Issue by kanishka8276** [Praful932/Kitabe#80]
**Describe the bug**
Clicking on Kitabe will direct you to the index page is not easily understood. Users are in a habit of using Home button. So to go to the home page they always look for the home button.

**Expected behavior**
A home button in the right where rest of the buttons are will be more user friendly.

**Are you willing to contribute to this issue?** [Yes/No]
Yes, I am a GsSOC'21 participant.

**Comment by Praful932** [comment]
@kanishka8276 Go ahead! Try to keep the icon theme consistent with other buttons :)

**Comment by kanishka8276** [comment]
Ok!

**Comment by simranbhalla3** [comment]
I am a gssoc'21 participant can i work on this issue?

**Comment by maneprajakta** [comment]
@simranbhalla3 It's already assigned to someone . Go through our [Guide](https://github.com/Praful932/Kitabe/discussions/42)
