### ISSUE TITLE
DEBUG variable in production

### ISSUE THREAD

**Issue by sneha-nitdgp** [Praful932/Kitabe#89]
**Describe the bug**
Debug is set as true in `settings.py`. This may cause security vulnerabilities.

**Describe the solution you'd like**
set `DEBUG = False`

**Are you willing to contribute to this issue? [Yes/No]**
Yes, I want to contribute to this issue as a part of GSSOC'21.

**Desktop (please complete the following information):**
- OS: Windows
- Browser : Chrome

**Screenshots**
![kitabe](https://user-images.githubusercontent.com/68119292/111069679-33bf6500-84f4-11eb-9b34-d11f23f09ab6.PNG)

**Comment by maneprajakta** [comment]
@Praful932 what you say ?

**Comment by Praful932** [comment]
@sneha-nitdgp Would request you to please follow the issue template, refer any other issues and update the PR Description :)
Then I can assign it to you
you can add this line `DEBUG = False` in the condition [here](https://github.com/Praful932/Kitabe/blob/master/BookRecSystem/settings.py#L190)

**Comment by maneprajakta** [comment]
@sneha-nitdgp are you working on this?

**Comment by sneha-nitdgp** [comment]
@maneprajakta Yeah, but I'm facing certain troubles. Please give some more time.

**Comment by maneprajakta** [comment]
@sneha-nitdgp  No issues

**Comment by maneprajakta** [comment]
@sneha-nitdgp any updates?

**Comment by varunkmr19** [comment]
Hi, I'm a GSSOC'21 Participant. Can I work on this if it's still open?

**Comment by Praful932** [comment]
Sure go ahead @varunkmr19

**Comment by maneprajakta** [comment]
closed by #140
