### ISSUE TITLE
Improve UI for book list under different genre

### ISSUE THREAD

**Issue by anjali494** [Praful932/Kitabe#90]
**Is your feature request related to a problem? Please describe.**
The Book Title for some books overflows the text box which makes the page look messy and confusing.
Also, when you hover over the picture, it slightly enlarges which makes it look like a clickable element.

**Describe the solution you'd like**
The white background should be resized to fit the content in it. Also, change the css of the buttons to make the page more user-friendly by changing layout or adding features like hover.

**Are you willing to contribute to this issue?** [Yes/No]
I am a participant of GSSOC'21 and would love to work on this issue

**Describe alternatives you've considered**
we can make the lists under genre similar to list under the explore page.

**Additional context**

like the buttons here hide some of the text.

![image](https://user-images.githubusercontent.com/76740314/111061789-08745000-84cb-11eb-8cb5-fae73c79d50e.png)

Whereas, the explore page has this layout.

![image](https://user-images.githubusercontent.com/76740314/111061775-e975be00-84ca-11eb-9c11-9d440a56c6ae.png)

**Comment by maneprajakta** [comment]
@anjali494 Please follow the issue template while creating an issue.
I have edited the issue description update accordingly.
Check this #58  what we aspect in an issue template.
If you update we will assign this to you.

**Comment by Praful932** [comment]
@anjali494 If you could attach a SS what is happening & what you expect, that would make the issue clearer

**Comment by anjali494** [comment]
@maneprajakta @Praful932 i edited the issue to make it more precise. Please check it out.

**Comment by maneprajakta** [comment]
@anjali494 what I could get is that you want to change the design of the genre book card to what is it on explore page.
Or anything else?

**Comment by anjali494** [comment]
@maneprajakta yes, it would solve the above mentioned issue.

**Comment by maneprajakta** [comment]
@anjali494 We don't want the card design to be changed for the genre page. If you could suggest other alternatives like one could be fixing the no of lines to be displayed for book name.

**Comment by Tarun-Kamboj** [comment]
Yes @maneprajakta, we should limit the text displayed on both `genre` and `explore` pages so that it don't exceed to the point where it starts looking bad. 
And regarding the enlargement of the image on hover, we can open the `details`  box when user clicks the image as it is a common practice to click on the image to know more about it.
@Praful932 I'd like to give this a go.

**Comment by Tarun-Kamboj** [comment]
@Praful932, @maneprajakta Can you assign this issue to me? I'm a GSSOC21 participant too.

**Comment by anjali494** [comment]
@maneprajakta we can add a feature that if the name of the book exceeds a number of characters, we can use ...

**Comment by maneprajakta** [comment]
@anjali494 got for it then.

**Comment by maneprajakta** [comment]
@Tarun-Kamboj thanks for showing interest.
Readout guidelines that we follow [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42)

**Comment by maneprajakta** [comment]
@anjali494 draft a PR for changes done till now.

**Comment by Mus2413** [comment]
Hello, I am Gssoc'21 participant . I would like to contribute on this project. Could you please assign me this issue.

**Comment by maneprajakta** [comment]
#148 will solve this
