### ISSUE TITLE
Migration bug in setting up commands

### ISSUE THREAD

**Issue by kanishka8276** [Praful932/Kitabe#91]
**Describe the bug**
Make migrations comment shows error when ran without making the mentioned changes in settings.py.
So in contributing.md we have to move the make migrations step after the step to make changes in settings.py

**Are you willing to contribute to this issue?** [Yes/No]
Yes, I am a GsSOC'21 participant.
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome

**Comment by maneprajakta** [comment]
@kanishka8276 Go ahead with this one.
