### ISSUE TITLE
Create a Fixed Header on Scroll

### ISSUE THREAD

**Issue by lavanya243** [Praful932/Kitabe#96]
Hey @Praful932, @SandeepKrSuman @Abg4real  , I am Lavanya Narayanan, a GSSOC, 2021 participant.
I want to create a fixed header on scroll, ie., whenever we scroll down the page, the header section remains fixed.

I would like to request you to kindly assign me this problem.

**Comment by maneprajakta** [comment]
we don't need this feature as issue #63 will solve this problem.
